
/********************************************
	Tabella Arcipelago 009 
	UDO CONVENZIONE
********************************************/

LIBNAME FAR_2016 '/sasprd/staging/staging_san1/S1_ORPSS/config/FAR_2016';
LIBNAME FAR_2017 '/sasprd/staging/staging_san1/S1_ORPSS/config/FAR_2017';
%include '/sasprd/staging/staging_san1/S1_ORPSS/config/MACRO_ORPSS/far_udo_atti.sas' ;

%MACRO SET_ADT_FAR;
proc sql;
	create table adt as
		select *
			from DWHODD.ODD_FAR_UNI_A4_DEF
				where (anno=&anno and fase =&fase  AND flg_archivio ne 'C');
quit;

DATA adt;
	SET adt;
	DATARIC_STRUTTURA_TEMP=INPUT(DATA_INGRESSO,DDMMYY8.);
	DATARIC_UDO_TEMP=INPUT(DATA_INGRESSO_UDO,DDMMYY8.);
	DATADIM_UDO_TEMP=INPUT(DATA_DIMISSIONE,DDMMYY8.);
	DATA_CONTRIBUTO_IN_TEMP=INPUT(DATA_CONTRIBUTO_IN,DDMMYY8.);
	DATA_CONTRIBUTO_FI_TEMP=INPUT(DATA_CONTRIBUTO_FI,DDMMYY8.);
	FORMAT DATARIC_STRUTTURA_TEMP DATARIC_UDO_TEMP 
		DATADIM_UDO_TEMP DATA_CONTRIBUTO_IN_TEMP DATA_CONTRIBUTO_FI_TEMP DATE9.;
RUN;

DATA adt;
	SET adt;
	DROP DATA_INGRESSO DATA_INGRESSO_UDO DATA_DIMISSIONE DATA_CONTRIBUTO_IN DATA_CONTRIBUTO_FI;
	RENAME PRG_REC=PRG_REC_A4
		ANNO=ANNO_A4
		COD_ENTE=ULSS
		ID_ASSISTITO=ID_EPISODIO
		COD_STRUT_EROG_UDO=COD_UDO
		COD_STRUT_EROG_STS=COD_STS
		COD_STRUT_EROG_MRA=COD_MRA
		COD_ASL_IMPEGNATIVA=ULSS_IMPEGNATIVA
		COD_PROVENIENZA=PROVENIENZA
		DATARIC_STRUTTURA_TEMP=DATARIC_STRUTTURA
		DATARIC_UDO_TEMP=DATARIC_UDO
		DATADIM_UDO_TEMP=DATADIM_UDO
		DATA_CONTRIBUTO_IN_TEMP=DATA_CONTRIBUTO_IN
		DATA_CONTRIBUTO_FI_TEMP=DATA_CONTRIBUTO_FI
		FASE=FASE_A4;
	FORMAT PROVENIENZA $PROVENIENZA.;
	FORMAT COD_RICHIESTA_INSERIMENTO $INIZIATIVA_INSERIMENTO. 
		VAL_RICHIESTA_INSERIMENTO $si_no_attesa. TITOLO_INGRESSO $titolo_ingresso. 
		cod_quota_rilievo $quota. cod_soggetto_pagante $sogg_pagante. 
		cod_tipo_dimissione $dimissione.;
run;

DATA adt;
	SET adt;
	VALORE_QUOTA_RILIEVO_num 		= input (VALORE_QUOTA_RILIEVO, best6.);
	TOTALE_QUOTA_GIORNALIERA_num 	= input (TOTALE_QUOTA_GIORNALIERA, best6.);
	COMPONENTE_SANITARIA_QUOTA_num	= input (COMPONENTE_SANITARIA_QUOTA, best6.);
run;

data adt;
	set adt;
	drop VALORE_QUOTA_RILIEVO TOTALE_QUOTA_GIORNALIERA COMPONENTE_SANITARIA_QUOTA;
run;
%MEND;


%macro set_assenze;
proc sql;
	create table assenze as
		select *
			from DWHODD.ODD_FAR_UNI_A5_DEF
				where ( flg_err=0  AND flg_archivio ne 'C' and anno=&anno and fase=&fase );
quit;


DATA ASSENZE;
	SET ASSENZE;
	DATA_IN_ASSENZA_TEMP2=INPUT(DATA_IN_ASSENZA_TEMP,DDMMYY8.);
	DATA_FI_ASSENZA_TEMP2=INPUT(DATA_FI_ASSENZA_TEMP,DDMMYY8.);
	FORMAT DATA_IN_ASSENZA_TEMP2 DATA_FI_ASSENZA_TEMP2 DATE9.;
RUN;

DATA ASSENZE;
	SET ASSENZE;
	DROP DATA_IN_ASSENZA_TEMP DATA_FI_ASSENZA_TEMP;
	RENAME PRG_REC=PRG_REC_A5
		COD_ENTE=ULSS
		ID_ASSISTITO=ID_EPISODIO
		COD_STRUT_EROG_UDO=COD_UDO
		DATA_IN_ASSENZA_TEMP2=DATA_IN_ASSENZA_TEMP
		DATA_FI_ASSENZA_TEMP2=DATA_FI_ASSENZA_TEMP
		FASE=FASE_A5;
	FORMAT COD_MOTIVAZIONE_ASSENZA $MOTIVO_ASSENZA.;
RUN;
data assenze;
	set assenze;
	ULSS_42=INPUT(ULSS,BEST3.);
run;
%mend; 


%macro SET_CONVENZIONE;
proc sql;
	create table udo_conv as
		select *
			from DWHODD.ODD_FAR_UNI_C0_IMPORT
				where (anno=&anno and flg_err=0 and fase =&fase_cds);
quit;


DATA udo_conv;set udo_conv;
RENAME PRG_REC=PRG_REC_C0
          COD_ENTE=ULSS
          COD_STRUT_EROG_UDO=COD_UDO
          COD_STRUT_EROG_STS=COD_STS
          COD_STRUT_EROG_MRA=COD_MRA
          COSTO_COORD_GERIATRIA=COSTO_COORD_GERIAT
          COSTO_RIABILITAZIONE=COSTO_RIABIL
          COSTO_FISIATRA=COSTO_FISIAT
          COSTO_ALIMENTAZIONE=COSTO_ALIMENT
          FLG_TITOLARE_CONV=FLG_TITOL_CONV
		  FASE=FASE_C0;RUN;

DATA udo_conv;set udo_conv;
FORMAT FLG_TITOL_CONV $CONVENZIONE.;RUN;

%MEND; 

%macro tabella_009;
/*attacco 7.1
/*???fai girare prima la tabella arcipelago 11*/

data udo;
	set udo;
	RENAME 	ANNO=ANNO_A7 ;
run;

proc sort data=udo;
	by cod_udo;
run;

proc sort data=udo_conv;
	by cod_udo;
run;

DATA conv_udo;/**/
	MERGE udo_conv (IN=A) UDO (IN=B);
	BY cod_udo;
	IF A and b;
RUN;

DATA conv_udo;
	set conv_udo;
	COSTO_MMG_NUM=INPUT(COSTO_MMG,BEST12.);
	COSTO_COORD_GERIATRIA_NUM=INPUT(COSTO_COORD_GERIAT,BEST12.);
	COSTO_RIABILITAZIONE_NUM=INPUT(COSTO_RIABIL,BEST12.);
	COSTO_FISIATRA_NUM=INPUT(COSTO_FISIAT,BEST12.);
	COSTO_FARMACI_NUM=INPUT(COSTO_FARMACI,BEST12.);
	COSTO_ALIMENTAZIONE_NUM=INPUT(COSTO_ALIMENT,BEST12.);
	COSTO_GUANTI_NUM=INPUT(COSTO_GUANTI,BEST12.);
	COSTO_PROTESI_NUM=INPUT(COSTO_PROTESI,BEST12.);
RUN;

DATA conv_udo;
	set conv_udo;
	DROP
		COSTO_MMG
		COSTO_COORD_GERIAT
		COSTO_RIABIL
		COSTO_FISIAT
		COSTO_FARMACI
		COSTO_ALIMENT
		COSTO_GUANTI
		COSTO_PROTESI;
RUN;

data conv_udo;
	set conv_udo;
	drop anno_rilevazione;
run;

data conv_udo;
	set conv_udo;
	anno_rilevazione=cats(&anno,'00');
run;

data conv_udo;
	set conv_udo;

	if ULSS_UDO='101' THEN
		ULSS_UDO_NEW=501;

	if ULSS_UDO='102' THEN
		ULSS_UDO_NEW=501;

	*;
	if ULSS_UDO='109' THEN
		ULSS_UDO_NEW=502;

	if ULSS_UDO='107' THEN
		ULSS_UDO_NEW=502;

	if ULSS_UDO='108' THEN
		ULSS_UDO_NEW=502;

	*;
	if ULSS_UDO='112' THEN
		ULSS_UDO_NEW=503;

	if ULSS_UDO='113' THEN
		ULSS_UDO_NEW=503;

	if ULSS_UDO='114' THEN
		ULSS_UDO_NEW=503;

	*;
	if ULSS_UDO='110' THEN
		ULSS_UDO_NEW=504;

	*;
	if ULSS_UDO='118' THEN
		ULSS_UDO_NEW=505;

	if ULSS_UDO='119' THEN
		ULSS_UDO_NEW=505;

	*;
	if ULSS_UDO='115' THEN
		ULSS_UDO_NEW=506;

	if ULSS_UDO='116' THEN
		ULSS_UDO_NEW=506;

	if ULSS_UDO='117' THEN
		ULSS_UDO_NEW=506;

	*;
	if ULSS_UDO='103' THEN
		ULSS_UDO_NEW=507;

	if ULSS_UDO='104' THEN
		ULSS_UDO_NEW=507;

	*;
	if ULSS_UDO='106' THEN
		ULSS_UDO_NEW=508;

	if ULSS_UDO='105' THEN
		ULSS_UDO_NEW=508;

	*;
	if ULSS_UDO='120' THEN
		ULSS_UDO_NEW=509;

	if ULSS_UDO='121' THEN
		ULSS_UDO_NEW=509;

	if ULSS_UDO='122' THEN
		ULSS_UDO_NEW=509;

	if ULSS_UDO='501' THEN
		ULSS_UDO_NEW=501;
	if ULSS_UDO='502' THEN
		ULSS_UDO_NEW=502;
	if ULSS_UDO='503' THEN
		ULSS_UDO_NEW=503;
	if ULSS_UDO='504' THEN
		ULSS_UDO_NEW=504;
	if ULSS_UDO='505' THEN
		ULSS_UDO_NEW=505;
	if ULSS_UDO='506' THEN
		ULSS_UDO_NEW=506;
	if ULSS_UDO='507' THEN
		ULSS_UDO_NEW=507;
	if ULSS_UDO='508' THEN
		ULSS_UDO_NEW=508;
	if ULSS_UDO='509' THEN
		ULSS_UDO_NEW=509;
RUN;

data conv_udo;
	set conv_udo;
	COSTO_TOTALE=
		COSTO_MMG_NUM+
		COSTO_COORD_GERIATRIA_NUM+
		COSTO_RIABILITAZIONE_NUM+
		COSTO_FISIATRA_NUM+
		COSTO_FARMACI_NUM+
		COSTO_ALIMENTAZIONE_NUM+
		COSTO_GUANTI_NUM+
		COSTO_PROTESI_NUM;
RUN;

/*CALCOLO LE GIORNATE DI ASSENZA PER UDO*/

data assenze;
	set assenze;

	if (DATA_FI_ASSENZA_TEMP ne . and DATA_IN_ASSENZA_TEMP ne .) then
		giorni_assenza_lordi = (DATA_FI_ASSENZA_TEMP - DATA_IN_ASSENZA_TEMP)+1;
run;

/*SOMMO I GIORNI DI ASSENZA PER COD_UDO*/
PROC SQL;
	create table DURATA_ASSENZE
		as SELECT DISTINCT  COD_UDO, 
			SUM(giorni_assenza_lordi) AS SUM_giorni_assenza_lordi
		FROM ASSENZE GROUP BY COD_UDO;
QUIT;


/*RICREO LE DATE PER IL CONTEGGIO DEI GIORNI LORDI DI PERMANENZA in adt*/

proc sort data=adt;
	by cod_udo;
run;

proc sort data=udo;
	by cod_udo;
run;

DATA au;/**/
	MERGE adt (IN=A) UDO (IN=B);
	BY cod_udo;

	IF A ;
RUN;

DATA AU;
	SET AU;
	ANNO_PRIMO_INGRESSO=YEAR(DATARIC_STRUTTURA);
	ANNO_INGRESSO_UDO=YEAR(DATARIC_UDO);
	ANNO_DIMISSIONE=YEAR(DATADIM_UDO);
RUN;

/*RICREO LE DATE PER IL CONTEGGIO DEI GIORNI LORDI DI PERMANENZA*/
DATA AU;
	SET AU;

	IF ANNO_INGRESSO_UDO<&anno THEN
		DATARIC_UDO_NEW=mdy(01,01,&anno);

	IF ANNO_INGRESSO_UDO=&anno THEN
		DATARIC_UDO_NEW=DATARIC_UDO;

	IF DATADIM_UDO=. or ANNO_DIMISSIONE = (&anno+1) THEN
		DATADIM_UDO_NEW=mdy(12,31,&anno);

	IF ANNO_DIMISSIONE=&anno THEN
		DATADIM_UDO_NEW=DATADIM_UDO;
	FORMAT DATADIM_UDO_NEW DATARIC_UDO_NEW DATE9.;
RUN;

DATA AU;
	SET AU;
	GIORNI_LORDI_&anno = (DATADIM_UDO_NEW - DATARIC_UDO_NEW) +1;
RUN;

DATA AU;
	SET AU;

	IF GIORNI_LORDI_&anno = 366 THEN
		GIORNI_LORDI = 365;
	ELSE GIORNI_LORDI = GIORNI_LORDI_&anno;
RUN;

DATA AU;
	SET AU;
	UT_EQ_LORDO	= GIORNI_LORDI/365;
RUN;

/*CALCOLO GLI UTENTI EQUIVALENTI LORDI PER UDO*/
/******++++++*****/
proc summary data=au nway;
class COD_UDO; 
var UT_EQ_LORDO GIORNI_LORDI;
output out=UT_EQ_UDO (drop= _type_ _freq_)
sum(UT_EQ_LORDO)=SUM_UT_EQ_LORDI sum(GIORNI_LORDI)=SUM_GG_LORDI; 
run; 

/*
PROC SQL;
	create table UT_EQ_UDO
		as SELECT DISTINCT COD_UDO, 
			SUM(UT_EQ_LORDO) AS SUM_UT_EQ_LORDI, 
			SUM(GIORNI_LORDI) AS SUM_GG_LORDI 
		FROM au GROUP BY COD_UDO;
QUIT;

/*UNISCO I DB PER CALCOLARE UTENTI EQUIVALENTI NETTI*/
proc sort data=UT_EQ_UDO;
	by cod_udo;
run;

proc sort data=DURATA_ASSENZE;
	by cod_udo;
run;

DATA DIFFERENZE_GG;/**/
	MERGE UT_EQ_UDO (IN=A) DURATA_ASSENZE (IN=B);
	BY cod_udo;

	IF A;
RUN;

DATA DIFFERENZE_GG;
	SET DIFFERENZE_GG;

	IF SUM_giorni_assenza_lordi=. THEN
		SUM_giorni_assenza_lordi=0;
RUN;

DATA DIFFERENZE_GG;
	SET DIFFERENZE_GG;

	IF SUM_giorni_assenza_lordi <= SUM_GG_LORDI THEN
		GIORNI_NETTI = (SUM_GG_LORDI - SUM_giorni_assenza_lordi);
	ELSE GIORNI_NETTI = 0;
RUN;

/*UTENTI EQUIVALENTI NETTI*/
DATA DIFFERENZE_GG;
	SET DIFFERENZE_GG;

	IF GIORNI_NETTI NE . THEN
		UT_EQ_NETTI = (GIORNI_NETTI/365.25);
RUN;

/**/

proc sort data=conv_udo;
	by cod_udo;
run;

proc sort data=differenze_gg;
	by cod_udo;
run;

DATA conv_udo_gg;/**/
	MERGE conv_udo (IN=A) differenze_gg (IN=B);
	BY cod_udo;

	IF A;
RUN;

*;
data conv_udo_gg;
	set conv_udo_gg;

	if SUM_UT_EQ_LORDI ne . then
		COSTO_MMG_365 = (COSTO_MMG_NUM/SUM_UT_EQ_LORDI)/365;

	if SUM_UT_EQ_LORDI ne . then
		COSTO_COORD_GERIATRIA_365 = (COSTO_COORD_GERIATRIA_NUM / SUM_UT_EQ_LORDI)/365;

	if SUM_UT_EQ_LORDI ne . then
		COSTO_RIABILITAZIONE_365 = (COSTO_RIABILITAZIONE_NUM / SUM_UT_EQ_LORDI)/365;

	if SUM_UT_EQ_LORDI ne . then
		COSTO_FISIATRA_365 = (COSTO_FISIATRA_NUM / SUM_UT_EQ_LORDI)/365;

	if SUM_UT_EQ_LORDI ne . then
		COSTO_FARMACI_365 = (COSTO_FARMACI_NUM / SUM_UT_EQ_LORDI)/365;

	if SUM_UT_EQ_LORDI ne . then
		COSTO_ALIMENTAZIONE_365 = (COSTO_ALIMENTAZIONE_NUM / SUM_UT_EQ_LORDI)/365;

	if SUM_UT_EQ_LORDI ne . then
		COSTO_GUANTI_365 = (COSTO_GUANTI_NUM / SUM_UT_EQ_LORDI)/365;

	if SUM_UT_EQ_LORDI ne . then
		COSTO_PROTESI_365 = (COSTO_PROTESI_NUM / SUM_UT_EQ_LORDI)/365;

	if SUM_UT_EQ_LORDI ne . then
		COSTO_TOTALE_365 = (COSTO_TOTALE / SUM_UT_EQ_LORDI)/365;
RUN;

/*COSTO MEDIO REGIONALE
Calcolo del costo medio 
giornaliero regionale per utente equivalente LORDO (dato uguale in tutte le righe)
*/
data conv_udo_gg;
	set conv_udo_gg;
	COSTO_PER_UT_EQ = (COSTO_TOTALE /  SUM_UT_EQ_LORDI);
RUN;

proc means data=conv_udo_gg noprint;
	class ULSS_UDO;
	var  COSTO_PER_UT_EQ;
	output out=y (DROP= _FREQ_ _TYPE_) mean= COSTO_MEDIO_UT_EQ_x_ULSS;
run;



PROC SORT DATA=conv_udo_gg;
	BY ULSS_UDO;
RUN;/**/

PROC SORT DATA=Y;
	BY ULSS_UDO;
RUN;

data ARCIPELAGO9;
	MERGE conv_udo_gg (in=a) Y (in=b);
	BY ULSS_UDO;

	if a AND B;
RUN;
/*+++*/
/*VALORE MEDIO REGIONALE DAL DB "Y"*/
data y1; set y; where ulss_udo=''; run; 
data y1; set y1; drop ulss_udo; run; 
data y1; set y1; anno = &anno; run;
data y1; set y1; rename COSTO_MEDIO_UT_EQ_x_ULSS = costo_medio_ut_eq_reg; run; 

proc sort data=arcipelago9; by anno; run; 

data arcipelago9ok; merge arcipelago9 (in=a) y1 (in=b); by anno; if a and b; run; 

/*calcolo del costo medio per ULSS nuove*/
proc summary data=ARCIPELAGO9ok ;
	class ULSS_UDO_NEW;
	var  COSTO_PER_UT_EQ;
	output out=Z (drop= _type_ _freq_) mean= COSTO_MEDIO_ULSS_NEW;
run;



PROC SORT DATA=ARCIPELAGO9ok;
	BY ULSS_UDO_NEW;
RUN;/**/

PROC SORT DATA=Z;
	BY ULSS_UDO_NEW;
RUN;

data ARCIPELAGO9OKk;
	MERGE ARCIPELAGO9ok (in=a) Z (in=b);
	BY ULSS_UDO_NEW;
	if a AND B;
RUN;

/* ++++
*/
data ARCIPELAGO9OKK;
	set ARCIPELAGO9OKK;
	KEEP
		ULSS_UDO
		ULSS_UDO_NEW
		ANNO
		COD_UDO
		REG_PROVV_CDS
		REG_ENTE_GES
		COSTO_MMG_NUM
		COSTO_COORD_GERIATRIA_NUM
		COSTO_RIABILITAZIONE_NUM
		COSTO_FISIATRA_NUM
		COSTO_FARMACI_NUM
		COSTO_ALIMENTAZIONE_NUM
		COSTO_GUANTI_NUM
		COSTO_PROTESI_NUM
		COSTO_TOTALE
		FLG_TITOL_CONV
		SUM_UT_EQ_LORDI
		UT_EQ_NETTI
		COSTO_MMG_365 
		COSTO_COORD_GERIATRIA_365 
		COSTO_RIABILITAZIONE_365 
		COSTO_FISIATRA_365 
		COSTO_FARMACI_365 
		COSTO_ALIMENTAZIONE_365 
		COSTO_GUANTI_365 
		COSTO_PROTESI_365  
		COSTO_TOTALE_365 
		COSTO_MEDIO_UT_EQ_REG
		COSTO_MEDIO_UT_EQ_x_ULSS
		COSTO_MEDIO_ULSS_NEW
	;
RUN;

data ARCIPELAGO9OKK;
	RETAIN
		ULSS_UDO
		ULSS_UDO_NEW
		ANNO
		COD_UDO
		REG_PROVV_CDS
		REG_ENTE_GES
		COSTO_MMG_NUM
		COSTO_COORD_GERIATRIA_NUM
		COSTO_RIABILITAZIONE_NUM
		COSTO_FISIATRA_NUM
		COSTO_FARMACI_NUM
		COSTO_ALIMENTAZIONE_NUM
		COSTO_GUANTI_NUM
		COSTO_PROTESI_NUM
		COSTO_TOTALE
		FLG_TITOL_CONV
		SUM_UT_EQ_LORDI
		UT_EQ_NETTI
		COSTO_MMG_365 
		COSTO_COORD_GERIATRIA_365 
		COSTO_RIABILITAZIONE_365 
		COSTO_FISIATRA_365 
		COSTO_FARMACI_365 
		COSTO_ALIMENTAZIONE_365 
		COSTO_GUANTI_365 
		COSTO_PROTESI_365  
		COSTO_TOTALE_365 
		COSTO_MEDIO_UT_EQ_REG
		COSTO_MEDIO_UT_EQ_x_ULSS
		COSTO_MEDIO_ULSS_NEW;
	SET ARCIPELAGO9OKK;
RUN;
%mend; 


%let anno=2016;
%let fase=12; 
%let fase_cds=0;

%set_adt_far;
%set_udo;
%set_convenzione;
%set_assenze;
%tabella_009; 

/*PER ACCODAMENTO DI PIù ANNI*/
DATA TMP_2016; SET ARCIPELAGO9OKK; RUN; /*ANNO 2016*/

DATA TMP_2017; SET ARCIPELAGO9OKK; RUN; /*ANNO 2017 */

DATA ARCIPELAGO_009; SET TMP_2016 TMP_2017; RUN; 

/**eof*/

