/****************************************/
/* TABELLA ARCIPELAGO 8					*/
/* Dati di servizio per UDO 			*/
/****************************************/

LIBNAME FAR_2016 '/sasprd/staging/staging_san1/S1_ORPSS/config/FAR_2016';
LIBNAME FAR_2017 '/sasprd/staging/staging_san1/S1_ORPSS/config/FAR_2017';
LIBNAME ARCIPE '/sasprd/staging/staging_san1/S1_ORPSS/config/Arcipelago';

%include '/sasprd/staging/staging_san1/S1_ORPSS/config/MACRO_ORPSS/far_anagrafica_con_errori.sas' ;
%include '/sasprd/staging/staging_san1/S1_ORPSS/config/MACRO_ORPSS/far_udo_atti.sas' ;
%include '/sasprd/staging/staging_san1/S1_ORPSS/config/MACRO_ORPSS/far_adt_con_errori.sas' ;

%let anno=2017; 	/*anno di interesse*/
%let fase=12; 		/*fase di interesse*/
%let trimestre=4; 	/* trimestre di interesse */
%let fase_cds=0; 

%SET_ANAGRAFICA_FAR(&anno,&fase);
%SET_ADT_FAR(&anno,&fase);
%SET_UDO;

/*CDS*/
%macro set_cds;
proc sql;
	create table cds as
		select *
			from DWHODD.ODD_FAR_UNI_B0_IMPORT
where (anno=&anno and fase=&fase_cds); /*lascio sempre a 0*/
quit;/**/


data cds;
	set cds;
	rename COD_STRUT_EROG_UDO=COD_UDO;
run;


/*cast a numero delle variabili quantitative*/
DATA cds;
	SET cds;
	HH_SER_COORD_PD_NUM=INPUT(HH_SER_COORD_PD,BEST12.);
	HH_SER_OSS_PD_NUM=INPUT(HH_SER_OSS_PD,BEST12.);
	HH_SER_OSS_S_PD_NUM=INPUT(HH_SER_OSS_S_PD,BEST12.);
	HH_SER_INFER_PD_NUM=INPUT(HH_SER_INFER_PD,BEST12.);
	HH_SER_ASS_SOC_PD_NUM=INPUT(HH_SER_ASS_SOC_PD,BEST12.);
	HH_SER_EDU_PD_NUM=INPUT(HH_SER_EDU_PD,BEST12.);
	HH_SER_PSI_PD_NUM=INPUT(HH_SER_PSI_PD,BEST12.);
	HH_SER_MED_PD_NUM=INPUT(HH_SER_MED_PD,BEST12.);
	HH_SER_FISIAT_PD_NUM=INPUT(HH_SER_FISIAT_PD,BEST12.);
	HH_SER_FISIOT_PD_NUM=INPUT(HH_SER_FISIOT_PD,BEST12.);
	HH_FOR_COORD_PD_NUM=INPUT(HH_FOR_COORD_PD,BEST12.);
	HH_FOR_OSS_PD_NUM=INPUT(HH_FOR_OSS_PD,BEST12.);
	HH_FOR_OSS_S_PD_NUM=INPUT(HH_FOR_OSS_S_PD,BEST12.);
	HH_FOR_INFER_PD_NUM=INPUT(HH_FOR_INFER_PD,BEST12.);
	HH_FOR_ASS_SOC_PD_NUM=INPUT(HH_FOR_ASS_SOC_PD,BEST12.);
	HH_FOR_EDU_PD_NUM=INPUT(HH_FOR_EDU_PD,BEST12.);
	HH_FOR_PSI_PD_NUM=INPUT(HH_FOR_PSI_PD,BEST12.);
	HH_FOR_MED_PD_NUM=INPUT(HH_FOR_MED_PD,BEST12.);
	HH_FOR_FISIAT_PD_NUM=INPUT(HH_FOR_FISIAT_PD,BEST12.);
	HH_FOR_FISIOT_PD_NUM=INPUT(HH_FOR_FISIOT_PD,BEST12.);
	GG_MATERNITA_PD_NUM=INPUT(GG_MATERNITA_PD,BEST12.);
	HH_PULIZIE_PD_NUM=INPUT(HH_PULIZIE_PD,BEST12.);
	GG_MALATTIA_PD_NUM=INPUT(GG_MALATTIA_PD,BEST12.);
	HH_SER_COORD_PND_NUM=INPUT(HH_SER_COORD_PND,BEST12.);
	HH_SER_OSS_PND_NUM=INPUT(HH_SER_OSS_PND,BEST12.);
	HH_SER_OSS_S_PND_NUM=INPUT(HH_SER_OSS_S_PND,BEST12.);
	HH_SER_INFER_PND_NUM=INPUT(HH_SER_INFER_PND,BEST12.);
	HH_SER_ASS_SOC_PND_NUM=INPUT(HH_SER_ASS_SOC_PND,BEST12.);
	HH_SER_EDU_PND_NUM=INPUT(HH_SER_EDU_PND,BEST12.);
	HH_SER_PSI_PND_NUM=INPUT(HH_SER_PSI_PND,BEST12.);
	HH_SER_MED_PND_NUM=INPUT(HH_SER_MED_PND,BEST12.);
	HH_SER_FISIAT_PND_NUM=INPUT(HH_SER_FISIAT_PND,BEST12.);
	HH_SER_FISIOT_PND_NUM=INPUT(HH_SER_FISIOT_PND,BEST12.);
	HH_FOR_COORD_PND_NUM=INPUT(HH_FOR_COORD_PND,BEST12.);
	HH_FOR_OSS_PND_NUM=INPUT(HH_FOR_OSS_PND,BEST12.);
	HH_FOR_OSS_S_PND_NUM=INPUT(HH_FOR_OSS_S_PND,BEST12.);
	HH_FOR_INFER_PND_NUM=INPUT(HH_FOR_INFER_PND,BEST12.);
	HH_FOR_ASS_SOC_PND_NUM=INPUT(HH_FOR_ASS_SOC_PND,BEST12.);
	HH_FOR_EDU_PND_NUM=INPUT(HH_FOR_EDU_PND,BEST12.);
	HH_FOR_PSI_PND_NUM=INPUT(HH_FOR_PSI_PND,BEST12.);
	HH_FOR_MED_PND_NUM=INPUT(HH_FOR_MED_PND,BEST12.);
	HH_FOR_FISIAT_PND_NUM=INPUT(HH_FOR_FISIAT_PND,BEST12.);
	HH_FOR_FISIOT_PND_NUM=INPUT(HH_FOR_FISIOT_PND,BEST12.);
	HH_ASS_DIR_PER_VOL_NUM=INPUT(HH_ASS_DIR_PER_VOL,BEST12.);
	GG_APERTURA_CD_NUM=INPUT(GG_APERTURA_CD,BEST12.);
	HH_APERTURA_CD_NUM=INPUT(HH_APERTURA_CD,BEST12.);
RUN;

DATA cds;
	SET cds;
	COSTO_COORD_PD_NUM=INPUT(COSTO_COORD_PD,BEST12.);
	COSTO_OSS_PD_NUM=INPUT(COSTO_OSS_PD,BEST12.);
	COSTO_OSS_S_PD_NUM=INPUT(COSTO_OSS_S_PD,BEST12.);
	COSTO_INFER_PD_NUM=INPUT(COSTO_INFER_PD,BEST12.);
	COSTO_ASS_SOC_PD_NUM=INPUT(COSTO_ASS_SOC_PD,BEST12.);
	COSTO_EDU_PD_NUM=INPUT(COSTO_EDU_PD,BEST12.);
	COSTO_PSI_PD_NUM=INPUT(COSTO_PSI_PD,BEST12.);
	COSTO_MED_PD_NUM=INPUT(COSTO_MED_PD,BEST12.);
	COSTO_FISIAT_PD_NUM=INPUT(COSTO_FISIAT_PD,BEST12.);
	COSTO_FISIOT_PD_NUM=INPUT(COSTO_FISIOT_PD,BEST12.);
	COSTO_MATERNITA_PD_NUM=INPUT(COSTO_MATERNITA_PD,BEST12.);
	COSTO_MALATTIA_PD_NUM=INPUT(COSTO_MALATTIA_PD,BEST12.);
	COSTO_COORD_PND_NUM=INPUT(COSTO_COORD_PND,BEST12.);
	COSTO_OSS_PND_NUM=INPUT(COSTO_OSS_PND,BEST12.);
	COSTO_OSS_S_PND_NUM=INPUT(COSTO_OSS_S_PND,BEST12.);
	COSTO_INFER_PND_NUM=INPUT(COSTO_INFER_PND,BEST12.);
	COSTO_ASS_SOC_PND_NUM=INPUT(COSTO_ASS_SOC_PND,BEST12.);
	COSTO_EDU_PND_NUM=INPUT(COSTO_EDU_PND,BEST12.);
	COSTO_PSI_PND_NUM=INPUT(COSTO_PSI_PND,BEST12.);
	COSTO_MED_PND_NUM=INPUT(COSTO_MED_PND,BEST12.);
	COSTO_FISIAT_PND_NUM=INPUT(COSTO_FISIAT_PND,BEST12.);
	COSTO_FISIOT_PND_NUM=INPUT(COSTO_FISIOT_PND,BEST12.);
	COSTO_AUS_INCONT_NUM=INPUT(COSTO_AUS_INCONT,BEST12.);
	COSTO_AUS_ALTRO_NUM=INPUT(COSTO_AUS_ALTRO,BEST12.);
RUN;

DATA cds;
	SET cds;
	drop 
		HH_SER_COORD_PD
		HH_SER_OSS_PD
		HH_SER_OSS_S_PD
		HH_SER_INFER_PD
		HH_SER_ASS_SOC_PD
		HH_SER_EDU_PD
		HH_SER_PSI_PD
		HH_SER_MED_PD
		HH_SER_FISIAT_PD
		HH_SER_FISIOT_PD
		COSTO_COORD_PD
		COSTO_OSS_PD
		COSTO_OSS_S_PD
		COSTO_INFER_PD
		COSTO_ASS_SOC_PD
		COSTO_EDU_PD
		COSTO_PSI_PD
		COSTO_MED_PD
		COSTO_FISIAT_PD
		COSTO_FISIOT_PD
		HH_FOR_COORD_PD
		HH_FOR_OSS_PD
		HH_FOR_OSS_S_PD
		HH_FOR_INFER_PD
		HH_FOR_ASS_SOC_PD
		HH_FOR_EDU_PD
		HH_FOR_PSI_PD
		HH_FOR_MED_PD
		HH_FOR_FISIAT_PD
		HH_FOR_FISIOT_PD
		GG_MATERNITA_PD
		COSTO_MATERNITA_PD
		HH_PULIZIE_PD
		GG_MALATTIA_PD
		COSTO_MALATTIA_PD
		HH_SER_COORD_PND
		HH_SER_OSS_PND
		HH_SER_OSS_S_PND
		HH_SER_INFER_PND
		HH_SER_ASS_SOC_PND
		HH_SER_EDU_PND
		HH_SER_PSI_PND
		HH_SER_MED_PND
		HH_SER_FISIAT_PND
		HH_SER_FISIOT_PND
		COSTO_COORD_PND
		COSTO_OSS_PND
		COSTO_OSS_S_PND
		COSTO_INFER_PND
		COSTO_ASS_SOC_PND
		COSTO_EDU_PND
		COSTO_PSI_PND
		COSTO_MED_PND
		COSTO_FISIAT_PND
		COSTO_FISIOT_PND
		HH_FOR_COORD_PND
		HH_FOR_OSS_PND
		HH_FOR_OSS_S_PND
		HH_FOR_INFER_PND
		HH_FOR_ASS_SOC_PND
		HH_FOR_EDU_PND
		HH_FOR_PSI_PND
		HH_FOR_MED_PND
		HH_FOR_FISIAT_PND
		HH_FOR_FISIOT_PND
		COSTO_AUS_INCONT
		COSTO_AUS_ALTRO
		HH_ASS_DIR_PER_VOL
		GG_APERTURA_CD
		HH_APERTURA_CD;
RUN;
%mend; 



%macro set_assenze;
proc sql;
	create table assenze as
		select *
			from DWHODD.ODD_FAR_UNI_A5_DEF
				where (  flg_archivio ne 'C' and anno=&anno and fase=&fase );
quit;


DATA ASSENZE;
	SET ASSENZE;
	DATA_IN_ASSENZA_TEMP2=INPUT(DATA_IN_ASSENZA_TEMP,DDMMYY8.);
	DATA_FI_ASSENZA_TEMP2=INPUT(DATA_FI_ASSENZA_TEMP,DDMMYY8.);
	FORMAT DATA_IN_ASSENZA_TEMP2 DATA_FI_ASSENZA_TEMP2 DATE9.;
RUN;

DATA ASSENZE;
	SET ASSENZE;
	DROP DATA_IN_ASSENZA_TEMP DATA_FI_ASSENZA_TEMP;
	RENAME PRG_REC=PRG_REC_A5
		COD_ENTE=ULSS
		ID_ASSISTITO=ID_EPISODIO
		COD_STRUT_EROG_UDO=COD_UDO
		DATA_IN_ASSENZA_TEMP2=DATA_IN_ASSENZA_TEMP
		DATA_FI_ASSENZA_TEMP2=DATA_FI_ASSENZA_TEMP
		FASE=FASE_A5;
	FORMAT COD_MOTIVAZIONE_ASSENZA $MOTIVO_ASSENZA.;
RUN;
data assenze;
	set assenze;
	ULSS_42=INPUT(ULSS,BEST3.);
run;
%mend; 




%macro tabella_008; 

/*UNISCO aL TRACCIATO 7 */

proc sort data=udo;
	by cod_udo;
run;

proc sort data=CDS;
	by cod_udo;
run;

DATA CDS_UDO;/**/
	MERGE CDS (IN=A) udo (IN=B);
	BY cod_udo;

	IF A AND B;
RUN;

data CDS_UDO;
	set CDS_UDO;

	if ULSS_UDO='101' THEN
		ULSS_UDO_NEW=501;

	if ULSS_UDO='102' THEN
		ULSS_UDO_NEW=501;

	if ULSS_UDO='109' THEN
		ULSS_UDO_NEW=502;

	if ULSS_UDO='107' THEN
		ULSS_UDO_NEW=502;

	if ULSS_UDO='108' THEN
		ULSS_UDO_NEW=502;

	if ULSS_UDO='112' THEN
		ULSS_UDO_NEW=503;

	if ULSS_UDO='113' THEN
		ULSS_UDO_NEW=503;

	if ULSS_UDO='114' THEN
		ULSS_UDO_NEW=503;

	if ULSS_UDO='110' THEN
		ULSS_UDO_NEW=504;

	if ULSS_UDO='118' THEN
		ULSS_UDO_NEW=505;

	if ULSS_UDO='119' THEN
		ULSS_UDO_NEW=505;

	if ULSS_UDO='115' THEN
		ULSS_UDO_NEW=506;

	if ULSS_UDO='116' THEN
		ULSS_UDO_NEW=506;

	if ULSS_UDO='117' THEN
		ULSS_UDO_NEW=506;

	if ULSS_UDO='103' THEN
		ULSS_UDO_NEW=507;

	if ULSS_UDO='104' THEN
		ULSS_UDO_NEW=507;

	if ULSS_UDO='106' THEN
		ULSS_UDO_NEW=508;

	if ULSS_UDO='105' THEN
		ULSS_UDO_NEW=508;

	if ULSS_UDO='120' THEN
		ULSS_UDO_NEW=509;

	if ULSS_UDO='121' THEN
		ULSS_UDO_NEW=509;

	if ULSS_UDO='122' THEN
		ULSS_UDO_NEW=509;

	if ULSS_UDO='501' THEN ULSS_UDO_NEW=501;
	if ULSS_UDO='502' THEN ULSS_UDO_NEW=502;
	if ULSS_UDO='503' THEN ULSS_UDO_NEW=503;
	if ULSS_UDO='504' THEN ULSS_UDO_NEW=504;
	if ULSS_UDO='505' THEN ULSS_UDO_NEW=505;
	if ULSS_UDO='506' THEN ULSS_UDO_NEW=506;
	if ULSS_UDO='507' THEN ULSS_UDO_NEW=507;
	if ULSS_UDO='508' THEN ULSS_UDO_NEW=508;
	if ULSS_UDO='509' THEN ULSS_UDO_NEW=509;
RUN;

/*CALCOLO LE GIORNATE DI ASSENZA PER UDO*/

data assenze;
	set assenze;

	if (DATA_FI_ASSENZA_TEMP ne . and DATA_IN_ASSENZA_TEMP ne .) then
		giorni_assenza_lordi = (DATA_FI_ASSENZA_TEMP - DATA_IN_ASSENZA_TEMP)+1;
run;

/*SOMMO I GIORNI DI ASSENZA PER COD_UDO*/
PROC SQL;
	create table DURATA_ASSENZE
		as SELECT DISTINCT  COD_UDO, 
			SUM(giorni_assenza_lordi) AS SUM_giorni_assenza_lordi
		FROM ASSENZE GROUP BY COD_UDO;
QUIT;


/*RICREO LE DATE PER IL CONTEGGIO DEI GIORNI LORDI DI PERMANENZA in adt*/

proc sort data=adt;
	by cod_udo;
run;

proc sort data=udo;
	by cod_udo;
run;

DATA au;/**/
	MERGE adt (IN=A) UDO (IN=B);
	BY cod_udo;

	IF A ;
RUN;

DATA AU;
	SET AU;
	ANNO_PRIMO_INGRESSO=YEAR(DATARIC_STRUTTURA);
	ANNO_INGRESSO_UDO=YEAR(DATARIC_UDO);
	ANNO_DIMISSIONE=YEAR(DATADIM_UDO);
RUN;

/*RICREO LE DATE PER IL CONTEGGIO DEI GIORNI LORDI DI PERMANENZA*/
DATA AU;
	SET AU;

	IF ANNO_INGRESSO_UDO<&anno THEN
		DATARIC_UDO_NEW=mdy(01,01,&anno);

	IF ANNO_INGRESSO_UDO=&anno THEN
		DATARIC_UDO_NEW=DATARIC_UDO;

	IF DATADIM_UDO=. or ANNO_DIMISSIONE = (&anno+1) THEN
		DATADIM_UDO_NEW=mdy(12,31,&anno);

	IF ANNO_DIMISSIONE=&anno THEN
		DATADIM_UDO_NEW=DATADIM_UDO;
	FORMAT DATADIM_UDO_NEW DATARIC_UDO_NEW DATE9.;
RUN;

DATA AU;
	SET AU;
	GIORNI_LORDI_&anno = (DATADIM_UDO_NEW - DATARIC_UDO_NEW) +1;
RUN;


DATA AU;
	SET AU;
/*anno non bisesitle*/
	IF GIORNI_LORDI_&anno = 366 and (mod(&anno,4) ne 0) THEN
		GIORNI_LORDI_&anno = 365;
/*anno  bisesitle*/
		IF GIORNI_LORDI_&anno = 367 and (mod(&anno,4) eq 0) THEN
		GIORNI_LORDI_&anno = 366;
RUN;

data au;
set au;
/*anno non bisestile*/
if (mod(&anno,4) ne 0) and &fase=1 then denominatore = 31; 
if (mod(&anno,4) ne 0) and &fase=2 then denominatore = 31+28; 
if (mod(&anno,4) ne 0) and &fase=3 then denominatore = 31+28+31; 
if (mod(&anno,4) ne 0) and &fase=4 then denominatore = 31+28+31+30; 
if (mod(&anno,4) ne 0) and &fase=5 then denominatore = 31+28+31+30+31; 
if (mod(&anno,4) ne 0) and &fase=6 then denominatore = 31+28+31+30+31+30; 
if (mod(&anno,4) ne 0) and &fase=7 then denominatore = 31+28+31+30+31+30+31; 
if (mod(&anno,4) ne 0) and &fase=8 then denominatore = 31+28+31+30+31+30+31+31; 
if (mod(&anno,4) ne 0) and &fase=9 then denominatore = 31+28+31+30+31+30+31+31+30; 
if (mod(&anno,4) ne 0) and &fase=10 then denominatore = 31+28+31+30+31+30+31+31+30+31; 
if (mod(&anno,4) ne 0) and &fase=11 then denominatore = 31+28+31+30+31+30+31+31+30+31+30; 
if (mod(&anno,4) ne 0) and &fase=12 then denominatore = 31+28+31+30+31+30+31+31+30+31+30+31;  
/*anno bisestitle*/
if (mod(&anno,4) eq 0) and &fase=1 then denominatore = 31; 
if (mod(&anno,4) eq 0) and &fase=2 then denominatore = 31+29; 
if (mod(&anno,4) eq 0) and &fase=3 then denominatore = 31+29+31; 
if (mod(&anno,4) eq 0) and &fase=4 then denominatore = 31+29+31+30; 
if (mod(&anno,4) eq 0) and &fase=5 then denominatore = 31+29+31+30+31; 
if (mod(&anno,4) eq 0) and &fase=6 then denominatore = 31+29+31+30+31+30; 
if (mod(&anno,4) eq 0) and &fase=7 then denominatore = 31+29+31+30+31+30+31; 
if (mod(&anno,4) eq 0) and &fase=8 then denominatore = 31+29+31+30+31+30+31+31; 
if (mod(&anno,4) eq 0) and &fase=9 then denominatore = 31+29+31+30+31+30+31+31+30; 
if (mod(&anno,4) eq 0) and &fase=10 then denominatore = 31+29+31+30+31+30+31+31+30+31; 
if (mod(&anno,4) eq 0) and &fase=11 then denominatore = 31+29+31+30+31+30+31+31+30+31+30; 
if (mod(&anno,4) eq 0) and &fase=12 then denominatore = 31+29+31+30+31+30+31+31+30+31+30+31; 
run; 

/*tengo conto dei giorni feriali per la presenza in CD max 261*/
data au;
	set au;
	if  &fase=1 then denominatore_cd = 21.75;
if  &fase=2 then denominatore_cd = (21.75 * 2);
if  &fase=3 then denominatore_cd = (21.75 * 3);
if  &fase=4 then denominatore_cd = (21.75 * 4);
if  &fase=5 then denominatore_cd = (21.75 * 5);
if  &fase=6 then denominatore_cd = (21.75 * 6);
if  &fase=7 then denominatore_cd = (21.75 * 7);
if  &fase=8 then denominatore_cd = (21.75 * 8);
if  &fase=9 then denominatore_cd = (21.75 * 9);
if  &fase=10 then denominatore_cd = (21.75 * 10);
if  &fase=11 then denominatore_cd = (21.75 * 11);
if  &fase=12 then denominatore_cd = (21.75 * 12);

	if tipo_udo = '5' or tipo_udo = '12' then
		GIORNI_LORDI_&anno = intck('weekday',DATARIC_UDO_NEW,DATADIM_UDO_NEW)+1;
run;

DATA AU;
	SET AU;
	VAL_SAN_LORDO 				= GIORNI_LORDI_&anno * VALORE_QUOTA_RILIEVO_num;
	VAL_EC_SOCIALE_LORDO 		= GIORNI_LORDI_&anno * TOTALE_QUOTA_GIORNALIERA_num;
	VAL_EC_ALBERGHIERO_LORDO 	= GIORNI_LORDI_&anno * COMPONENTE_SANITARIA_QUOTA_num;

RUN;

DATA AU;
	SET AU;
	if (tipo_udo = '5' or tipo_udo = '12') then do;
		UT_EQ_LORDO	= GIORNI_LORDI_&anno / denominatore_cd; end;
	else do;
		UT_EQ_LORDO	= GIORNI_LORDI_&anno / denominatore; end; 
		run;

data au; set au; if ut_eq_lordo>1 then ut_eq_lordo=1; run; 


data au; set au; rename giorni_lordi_&anno=giorni_lordi; run; 

/*CALCOLO GLI UTENTI EQUIVALENTI LORDI PER UDO*/
/*PROC SQL;
	create table UT_EQ_UDO
		as SELECT DISTINCT COD_UDO, 
			SUM(UT_EQ_LORDO) AS SUM_UT_EQ_LORDI, 
			SUM(GIORNI_LORDI) AS SUM_GG_LORDI 
		FROM au GROUP BY COD_UDO;
QUIT;*/

proc summary data=au nway;
	class cod_udo;
	var UT_EQ_LORDO GIORNI_LORDI;
	output out=UT_EQ_UDO (drop = _type_ _freq_) 
sum(UT_EQ_LORDO)=SUM_UT_EQ_LORDI
sum(GIORNI_LORDI)=SUM_GG_LORDI;
run;

/*UNISCO I DB PER CALCOLARE UTENTI EQUIVALENTI NETTI*/
proc sort data=UT_EQ_UDO;
	by cod_udo;
run;

proc sort data=DURATA_ASSENZE;
	by cod_udo;
run;

DATA DIFFERENZE_GG;/**/
	MERGE UT_EQ_UDO (IN=A) DURATA_ASSENZE (IN=B);
	BY cod_udo;

	IF A;
RUN;

DATA DIFFERENZE_GG;
	SET DIFFERENZE_GG;

	IF SUM_giorni_assenza_lordi=. THEN
		SUM_giorni_assenza_lordi=0;
RUN;

DATA DIFFERENZE_GG;
	SET DIFFERENZE_GG;

	IF SUM_giorni_assenza_lordi <= SUM_GG_LORDI THEN
		GIORNI_NETTI = (SUM_GG_LORDI - SUM_giorni_assenza_lordi);
	ELSE GIORNI_NETTI = 0;
RUN;

/*UTENTI EQUIVALENTI NETTI*/
DATA DIFFERENZE_GG;
	SET DIFFERENZE_GG;

	IF GIORNI_NETTI NE . THEN
		UT_EQ_NETTI = (GIORNI_NETTI/365.25);
RUN;

proc sort data=CDS_UDO;
	by cod_udo;
run;

proc sort data=DIFFERENZE_GG;
	by cod_udo;
run;

DATA CDS_UDO_GG;/**/
	MERGE CDS_UDO (IN=A) DIFFERENZE_GG (IN=B);
	BY cod_udo;

	IF A;
RUN;




/*/`
*/
/*SOMMA ORE E COSTI PERSONALE DIPENDENTE E NON DIPENDENTE*/
DATA CDS_UDO_GG;
	SET CDS_UDO_GG;
	HH_SER_COORD=(HH_SER_COORD_PD_num+HH_SER_COORD_PND_num);
	HH_SER_OSS=(HH_SER_OSS_PD_num+HH_SER_OSS_S_PD_num+HH_SER_OSS_PND_num+HH_SER_OSS_S_PND_num);
	HH_SER_INFER=(HH_SER_INFER_PD_num+HH_SER_INFER_PND_num);
	HH_SER_ASS_SOC=(HH_SER_ASS_SOC_PD_num+HH_SER_ASS_SOC_PND_num);
	HH_SER_EDU=(HH_SER_EDU_PD_num+HH_SER_EDU_PND_num);
	HH_SER_PSI=(HH_SER_PSI_PD_num+HH_SER_PSI_PND_num);
	HH_SER_MED=(HH_SER_MED_PD_num+HH_SER_MED_PND_num);
	HH_SER_FISIAT=(HH_SER_FISIAT_PD_num+HH_SER_FISIAT_PND_num);
	HH_SER_FISIOT=(HH_SER_FISIOT_PD_num+HH_SER_FISIOT_PND_num);
	HH_FOR_COORD=(HH_FOR_COORD_PD_num+HH_FOR_COORD_PND_num);
	HH_FOR_OSS=(HH_FOR_OSS_PD_num+HH_FOR_OSS_S_PD_num+HH_FOR_OSS_PND_num+HH_FOR_OSS_S_PND_num);
	HH_FOR_INFER=(HH_FOR_INFER_PD_num+HH_FOR_INFER_PND_num);
	HH_FOR_ASS_SOC=(HH_FOR_ASS_SOC_PD_num+HH_FOR_ASS_SOC_PND_num);
	HH_FOR_EDU=(HH_FOR_EDU_PD_num+HH_FOR_EDU_PND_num);
	HH_FOR_PSI=(HH_FOR_PSI_PD_num+HH_FOR_PSI_PND_num);
	HH_FOR_MED=(HH_FOR_MED_PD_num+HH_FOR_MED_PND_num);
	HH_FOR_FISIAT=(HH_FOR_FISIAT_PD_num+HH_FOR_FISIAT_PND_num);
	HH_FOR_FISIOT=(HH_FOR_FISIOT_PD_num+HH_FOR_FISIOT_PND_num);
	COSTO_COORD = COSTO_COORD_PD_NUM+COSTO_COORD_PND_NUM;
	COSTO_OSS = COSTO_OSS_PD_NUM+COSTO_OSS_PND_NUM+COSTO_OSS_S_PD_NUM+COSTO_OSS_S_PND_NUM;
	COSTO_INFER = COSTO_INFER_PD_NUM+COSTO_INFER_PND_NUM;
	COSTO_ASS_SOC = COSTO_ASS_SOC_PD_NUM+COSTO_ASS_SOC_PND_NUM;
	COSTO_EDU = COSTO_EDU_PD_NUM+COSTO_EDU_PND_NUM;
	COSTO_PSI = COSTO_PSI_PD_NUM+COSTO_PSI_PND_NUM;
	COSTO_MED = COSTO_MED_PD_NUM+COSTO_MED_PND_NUM;
	COSTO_FISIAT = COSTO_FISIAT_PD_NUM+COSTO_FISIAT_PND_NUM;
	COSTO_FISIOT = COSTO_FISIOT_PD_NUM+COSTO_FISIOT_PND_NUM;
run;


/**/
DATA ARCIPELAGO8;
	SET CDS_UDO_GG;
	KEEP
		ULSS_UDO
		ULSS_UDO_NEW
		ANNO
		COD_UDO
		REG_PROVV_CDS
		REG_ENTE_GES
		HH_SER_COORD_PD_NUM
		HH_SER_OSS_PD_NUM
		HH_SER_OSS_S_PD_NUM
		HH_SER_INFER_PD_NUM
		HH_SER_ASS_SOC_PD_NUM
		HH_SER_EDU_PD_NUM
		HH_SER_PSI_PD_NUM
		HH_SER_MED_PD_NUM
		HH_SER_FISIAT_PD_NUM
		HH_SER_FISIOT_PD_NUM
		COSTO_COORD_PD_NUM
		COSTO_OSS_PD_NUM
		COSTO_OSS_S_PD_NUM
		COSTO_INFER_PD_NUM
		COSTO_ASS_SOC_PD_NUM
		COSTO_EDU_PD_NUM
		COSTO_PSI_PD_NUM
		COSTO_MED_PD_NUM
		COSTO_FISIAT_PD_NUM
		COSTO_FISIOT_PD_NUM
		HH_FOR_COORD_PD_NUM
		HH_FOR_OSS_PD_NUM
		HH_FOR_OSS_S_PD_NUM
		HH_FOR_INFER_PD_NUM
		HH_FOR_ASS_SOC_PD_NUM
		HH_FOR_EDU_PD_NUM
		HH_FOR_PSI_PD_NUM
		HH_FOR_MED_PD_NUM
		HH_FOR_FISIAT_PD_NUM
		HH_FOR_FISIOT_PD_NUM
		GG_MATERNITA_PD_NUM
		COSTO_MATERNITA_PD_NUM
		HH_PULIZIE_PD_NUM
		GG_MALATTIA_PD_NUM
		COSTO_MALATTIA_PD_NUM
		HH_SER_COORD_PND_NUM
		HH_SER_OSS_PND_NUM
		HH_SER_OSS_S_PND_NUM
		HH_SER_INFER_PND_NUM
		HH_SER_ASS_SOC_PND_NUM
		HH_SER_EDU_PND_NUM
		HH_SER_PSI_PND_NUM
		HH_SER_MED_PND_NUM
		HH_SER_FISIAT_PND_NUM
		HH_SER_FISIOT_PND_NUM
		COSTO_COORD_PND_NUM
		COSTO_OSS_PND_NUM
		COSTO_OSS_S_PND_NUM
		COSTO_INFER_PND_NUM
		COSTO_ASS_SOC_PND_NUM
		COSTO_EDU_PND_NUM
		COSTO_PSI_PND_NUM
		COSTO_MED_PND_NUM
		COSTO_FISIAT_PND_NUM
		COSTO_FISIOT_PND_NUM
		HH_FOR_COORD_PND_NUM
		HH_FOR_OSS_PND_NUM
		HH_FOR_OSS_S_PND_NUM
		HH_FOR_INFER_PND_NUM
		HH_FOR_ASS_SOC_PND_NUM
		HH_FOR_EDU_PND_NUM
		HH_FOR_PSI_PND_NUM
		HH_FOR_MED_PND_NUM
		HH_FOR_FISIAT_PND_NUM
		HH_FOR_FISIOT_PND_NUM
		COSTO_AUS_INCONT_NUM
		COSTO_AUS_ALTRO_NUM
		HH_ASS_DIR_PER_VOL_NUM
		SOMMA_POSTI_AUTO
		SUM_UT_EQ_LORDI
		UT_EQ_NETTI
	;
run;

data ARCIPELAGO8;
	RETAIN
		ULSS_UDO
		ULSS_UDO_NEW
		ANNO
		COD_UDO
		REG_PROVV_CDS
		REG_ENTE_GES
		HH_SER_COORD_PD_NUM
		HH_SER_OSS_PD_NUM
		HH_SER_OSS_S_PD_NUM
		HH_SER_INFER_PD_NUM
		HH_SER_ASS_SOC_PD_NUM
		HH_SER_EDU_PD_NUM
		HH_SER_PSI_PD_NUM
		HH_SER_MED_PD_NUM
		HH_SER_FISIAT_PD_NUM
		HH_SER_FISIOT_PD_NUM
		COSTO_COORD_PD_NUM
		COSTO_OSS_PD_NUM
		COSTO_OSS_S_PD_NUM
		COSTO_INFER_PD_NUM
		COSTO_ASS_SOC_PD_NUM
		COSTO_EDU_PD_NUM
		COSTO_PSI_PD_NUM
		COSTO_MED_PD_NUM
		COSTO_FISIAT_PD_NUM
		COSTO_FISIOT_PD_NUM
		HH_FOR_COORD_PD_NUM
		HH_FOR_OSS_PD_NUM
		HH_FOR_OSS_S_PD_NUM
		HH_FOR_INFER_PD_NUM
		HH_FOR_ASS_SOC_PD_NUM
		HH_FOR_EDU_PD_NUM
		HH_FOR_PSI_PD_NUM
		HH_FOR_MED_PD_NUM
		HH_FOR_FISIAT_PD_NUM
		HH_FOR_FISIOT_PD_NUM
		GG_MATERNITA_PD_NUM
		COSTO_MATERNITA_PD_NUM
		HH_PULIZIE_PD_NUM
		GG_MALATTIA_PD_NUM
		COSTO_MALATTIA_PD_NUM
		HH_SER_COORD_PND_NUM
		HH_SER_OSS_PND_NUM
		HH_SER_OSS_S_PND_NUM
		HH_SER_INFER_PND_NUM
		HH_SER_ASS_SOC_PND_NUM
		HH_SER_EDU_PND_NUM
		HH_SER_PSI_PND_NUM
		HH_SER_MED_PND_NUM
		HH_SER_FISIAT_PND_NUM
		HH_SER_FISIOT_PND_NUM
		COSTO_COORD_PND_NUM
		COSTO_OSS_PND_NUM
		COSTO_OSS_S_PND_NUM
		COSTO_INFER_PND_NUM
		COSTO_ASS_SOC_PND_NUM
		COSTO_EDU_PND_NUM
		COSTO_PSI_PND_NUM
		COSTO_MED_PND_NUM
		COSTO_FISIAT_PND_NUM
		COSTO_FISIOT_PND_NUM
		HH_FOR_COORD_PND_NUM
		HH_FOR_OSS_PND_NUM
		HH_FOR_OSS_S_PND_NUM
		HH_FOR_INFER_PND_NUM
		HH_FOR_ASS_SOC_PND_NUM
		HH_FOR_EDU_PND_NUM
		HH_FOR_PSI_PND_NUM
		HH_FOR_MED_PND_NUM
		HH_FOR_FISIAT_PND_NUM
		HH_FOR_FISIOT_PND_NUM
		COSTO_AUS_INCONT_NUM
		COSTO_AUS_ALTRO_NUM
		HH_ASS_DIR_PER_VOL_NUM
		SOMMA_POSTI_AUTO
		SUM_UT_EQ_LORDI
		UT_EQ_NETTI;
	SET ARCIPELAGO8;
RUN;
%mend; 

%set_cds;
%set_assenze;
%tabella_008;


/*PER ACCODAMENTO DI PIù ANNI*/
DATA TMP_2016; SET ARCIPELAGO8; RUN; /*ANNO 2016*/

DATA TMP_2017; SET ARCIPELAGO8; RUN; /*ANNO 2017*/

DATA ARCIPELAGO_008; SET TMP_2016 TMP_2017; RUN; 



