/**/
/************************************************/
/* 			Tabella 5 TER arcipelago 			*/
/*			Assenze per ricoveri ospedalieri 
/* 			Aggancio con SDO					*/
/************************************************/

LIBNAME FAR_2016 '/sasprd/staging/staging_san1/S1_ORPSS/config/FAR_2016';
LIBNAME FAR_2017 '/sasprd/staging/staging_san1/S1_ORPSS/config/FAR_2017';
LIBNAME FAR_2018 '/sasprd/staging/staging_san1/S1_ORPSS/config/FAR_2017';


%MACRO SET_ANAGRAFICA_FAR;
proc sql;
	create table ANA as
		select *
			from DWHODD.ODD_FAR_UNI_A1_DEF
				where (anno=&anno and fase =&fase  and flg_err=0 AND flg_archivio ne 'C');
quit;

data ana;
	set ana;
	DATANASC_TEMP=input(DATA_NASCITA,ddmmyy8.);
	DATA_CAMBIO_RES_TEMP=input(DATA_CAMBIO_RES,ddmmyy8.);
	format DATANASC_TEMP DATA_CAMBIO_RES_TEMP date9.;
run;

data ana;
	SET ana;
	drop DATA_NASCITA DATA_CAMBIO_RES;
	ULSS_A1=INPUT(COD_ENTE,BEST3.);
	ULSS_UDO_A1=INPUT(SUBSTR(COD_ASL_EROGATRICE,4,3),BEST3.);
	RENAME 
		ANNO= ANNO_A1
		PRG_REC=PRG_REC_A1
		CODICE_SOGGETTO=CODICE_SOGGETTO_BIN
		COD_ENTE=ULSS
		ID_ASSISTITO=ID_EPISODIO
		DATA_NASCITA=DATANASC
		CITTADINANZA=CITTAD
		TITOLO_STUDIO=ISTRUZIONE
		COD_REG_RES=REG_RES
		COD_ASL_RES=USL_RES
		COD_COMUNE_RES_IN=ISTRES_IN 
		COD_COMUNE_RES_OUT=ISTRES_OUT
		COD_ASL_EROGATRICE=ULSS_UDO 
		FLG_CHK_CODICE_FISCALE=FLG_CHK_CF
		FLG_CHK_CODICE_SSN=FLG_CHK_CODSAN
		FLG_CHK_COGNOME_E_NOME=FLG_CHK_CNOME 
		FLG_CHK_DATI_ANAG_CONGRUENTI=FLG_CHK_DATI_ANAG
		DATANASC_TEMP=DATANASC
		DATA_CAMBIO_RES_TEMP=DATA_CAMBIO_RES
		FASE=FASE_A1;
	run; 

data ana;
	SET ana;
	format 
		SESSO $SEX.
		ISTRUZIONE $istruzione.
		STATO_CIVILE $STA_CIV. 
		flg_tipo_utente $utente.
		tipo_id_utente $id_utente. 
		;
run;

data ana; set ana; 
drop ulss_udo; run; 

%MEND;


%MACRO SET_ADT_FAR;
proc sql;
	create table adt as
		select *
			from DWHODD.ODD_FAR_UNI_A4_DEF
				where (anno=&anno and fase =&fase  and flg_err=0 AND flg_archivio ne 'C');
quit;

DATA adt;
	SET adt;
	DATARIC_STRUTTURA_TEMP=INPUT(DATA_INGRESSO,DDMMYY8.);
	DATARIC_UDO_TEMP=INPUT(DATA_INGRESSO_UDO,DDMMYY8.);
	DATADIM_UDO_TEMP=INPUT(DATA_DIMISSIONE,DDMMYY8.);
	DATA_CONTRIBUTO_IN_TEMP=INPUT(DATA_CONTRIBUTO_IN,DDMMYY8.);
	DATA_CONTRIBUTO_FI_TEMP=INPUT(DATA_CONTRIBUTO_FI,DDMMYY8.);
	FORMAT DATARIC_STRUTTURA_TEMP DATARIC_UDO_TEMP 
		DATADIM_UDO_TEMP DATA_CONTRIBUTO_IN_TEMP DATA_CONTRIBUTO_FI_TEMP DATE9.;
RUN;

DATA adt;
	SET adt;
	DROP DATA_INGRESSO DATA_INGRESSO_UDO DATA_DIMISSIONE DATA_CONTRIBUTO_IN DATA_CONTRIBUTO_FI;
	RENAME PRG_REC=PRG_REC_A4
		ANNO=ANNO_A4
		COD_ENTE=ULSS
		ID_ASSISTITO=ID_EPISODIO
		COD_STRUT_EROG_UDO=COD_UDO
		COD_STRUT_EROG_STS=COD_STS
		COD_STRUT_EROG_MRA=COD_MRA
		COD_ASL_IMPEGNATIVA=ULSS_IMPEGNATIVA
		COD_PROVENIENZA=PROVENIENZA
		DATARIC_STRUTTURA_TEMP=DATARIC_STRUTTURA
		DATARIC_UDO_TEMP=DATARIC_UDO
		DATADIM_UDO_TEMP=DATADIM_UDO
		DATA_CONTRIBUTO_IN_TEMP=DATA_CONTRIBUTO_IN
		DATA_CONTRIBUTO_FI_TEMP=DATA_CONTRIBUTO_FI
		FASE=FASE_A4;
	FORMAT PROVENIENZA $PROVENIENZA.;
	FORMAT COD_RICHIESTA_INSERIMENTO $INIZIATIVA_INSERIMENTO. 
		VAL_RICHIESTA_INSERIMENTO $si_no_attesa. TITOLO_INGRESSO $titolo_ingresso. 
		cod_quota_rilievo $quota. cod_soggetto_pagante $sogg_pagante. 
		cod_tipo_dimissione $dimissione.;
run;

DATA adt;
	SET adt;
	VALORE_QUOTA_RILIEVO_num 		= input (VALORE_QUOTA_RILIEVO, best6.);
	TOTALE_QUOTA_GIORNALIERA_num 	= input (TOTALE_QUOTA_GIORNALIERA, best6.);
	COMPONENTE_SANITARIA_QUOTA_num	= input (COMPONENTE_SANITARIA_QUOTA, best6.);
run;

data adt;
	set adt;
	drop VALORE_QUOTA_RILIEVO TOTALE_QUOTA_GIORNALIERA COMPONENTE_SANITARIA_QUOTA;
run;
%MEND;

%MACRO SET_UDO;
/*CONTROLLARE CHE SIA AGGIORNATO IL FILE. 
EVENTUALMENTE FAR GIRARE anagrafica_udo che genera il file corretto*/
data udo;
	set FAR_&ANNO..ANAGRAFICA_UDO_POSTI_&ANNO.;
run;

DATA udo;
	SET udo;
	FORMAT TIPO_UDO $TIPOUDO. 
	COD_ATTO_ACCR $COD_ATTO.
	COD_ATTO_AUTO $COD_ATTO.
	;
run;
%MEND; 


/* IMPORTO IL DB ASSENZE*/
/* importo assenze */


%macro set_assenze;
proc sql;
	create table assenze as
		select *
			from DWHODD.ODD_FAR_UNI_A5_DEF
				where ( flg_err=0  AND flg_archivio ne 'C' and anno=&anno and fase=&fase );
quit;


DATA ASSENZE;
	SET ASSENZE;
	DATA_IN_ASSENZA_TEMP2=INPUT(DATA_IN_ASSENZA_TEMP,DDMMYY8.);
	DATA_FI_ASSENZA_TEMP2=INPUT(DATA_FI_ASSENZA_TEMP,DDMMYY8.);
	FORMAT DATA_IN_ASSENZA_TEMP2 DATA_FI_ASSENZA_TEMP2 DATE9.;
RUN;

DATA ASSENZE;
	SET ASSENZE;
	DROP DATA_IN_ASSENZA_TEMP DATA_FI_ASSENZA_TEMP;
	RENAME PRG_REC=PRG_REC_A5
		COD_ENTE=ULSS
		ID_ASSISTITO=ID_EPISODIO
		COD_STRUT_EROG_UDO=COD_UDO
		DATA_IN_ASSENZA_TEMP2=DATA_IN_ASSENZA_TEMP
		DATA_FI_ASSENZA_TEMP2=DATA_FI_ASSENZA_TEMP
		FASE=FASE_A5;
	FORMAT COD_MOTIVAZIONE_ASSENZA $MOTIVO_ASSENZA.;
RUN;
data assenze;
	set assenze;
	ULSS_42=INPUT(ULSS,BEST12.);
run;
%mend; 



%macro tabella_005_ter;
data ana;
	set ana;
	k=cats(ID_EPISODIO,ULSS_A1,CODICE_SOGGETTO_BIN);
RUN;

/*CALCOLO L'ETA' al 31/12/&anno*/
DATA ana;
	SET ana;
	eta=int((mdy(12,31,&anno)-DATANASC)/365);
run;

DATA ana;
	SET ana;

	if eta=. then
		cleta=.;

	if 0<=eta<=64 then
		cleta=1;

	if 65<=eta<=74 then
		cleta=2;

	if 75<=eta<=84 then
		cleta=3;

	if eta>=85 then
		cleta=4;
	format cleta fascia_eta.;
RUN;


data adt;
	set ADT;
	rename ulss= ULSS_A4;
RUN;

data adt;
	set adt;
	k=cats(ID_EPISODIO,ULSS_A4,CODICE_SOGGETTO_BIN);
run;

proc sort data=adt;
	by cod_udo;
run;

proc sort data=udo;
	by cod_udo;
run;

DATA au;
	MERGE adt (IN=A) UDO (IN=B);
	BY cod_udo;
	IF A;
RUN;


data au;
	set au;

	if ULSS_UDO='101' THEN
		ULSS_UDO_NEW=501;

	if ULSS_UDO='102' THEN
		ULSS_UDO_NEW=501;

	*;
	if ULSS_UDO='109' THEN
		ULSS_UDO_NEW=502;

	if ULSS_UDO='107' THEN
		ULSS_UDO_NEW=502;

	if ULSS_UDO='108' THEN
		ULSS_UDO_NEW=502;

	*;
	if ULSS_UDO='112' THEN
		ULSS_UDO_NEW=503;

	if ULSS_UDO='113' THEN
		ULSS_UDO_NEW=503;

	if ULSS_UDO='114' THEN
		ULSS_UDO_NEW=503;

	*;
	if ULSS_UDO='110' THEN
		ULSS_UDO_NEW=504;

	*;
	if ULSS_UDO='118' THEN
		ULSS_UDO_NEW=505;

	if ULSS_UDO='119' THEN
		ULSS_UDO_NEW=505;

	*;
	if ULSS_UDO='115' THEN
		ULSS_UDO_NEW=506;

	if ULSS_UDO='116' THEN
		ULSS_UDO_NEW=506;

	if ULSS_UDO='117' THEN
		ULSS_UDO_NEW=506;

	*;
	if ULSS_UDO='103' THEN
		ULSS_UDO_NEW=507;

	if ULSS_UDO='104' THEN
		ULSS_UDO_NEW=507;

	*;
	if ULSS_UDO='106' THEN
		ULSS_UDO_NEW=508;

	if ULSS_UDO='105' THEN
		ULSS_UDO_NEW=508;

	*;
	if ULSS_UDO='120' THEN
		ULSS_UDO_NEW=509;

	if ULSS_UDO='121' THEN
		ULSS_UDO_NEW=509;

	if ULSS_UDO='122' THEN
		ULSS_UDO_NEW=509;
RUN;

DATA AU;
	SET AU;
	DUMMY=SUBSTR(ULSS_IMPEGNATIVA,1,3);
RUN;

DATA AU;
	SET AU;

	IF DUMMY='050' THEN
		ULSS_IMPEGNATIVA_OLD=SUBSTR(ULSS_IMPEGNATIVA, 4,3);
RUN;

data au;
	set au;

	if ULSS_IMPEGNATIVA_OLD='101' THEN
		ULSS_IMPEGNATIVA_NEW=501;

	if ULSS_IMPEGNATIVA_OLD='102' THEN
		ULSS_IMPEGNATIVA_NEW=501;

	*;
	if ULSS_IMPEGNATIVA_OLD='109' THEN
		ULSS_IMPEGNATIVA_NEW=502;

	if ULSS_IMPEGNATIVA_OLD='107' THEN
		ULSS_IMPEGNATIVA_NEW=502;

	if ULSS_IMPEGNATIVA_OLD='108' THEN
		ULSS_IMPEGNATIVA_NEW=502;

	*;
	if ULSS_IMPEGNATIVA_OLD='112' THEN
		ULSS_IMPEGNATIVA_NEW=503;

	if ULSS_IMPEGNATIVA_OLD='113' THEN
		ULSS_IMPEGNATIVA_NEW=503;

	if ULSS_IMPEGNATIVA_OLD='114' THEN
		ULSS_IMPEGNATIVA_NEW=503;

	*;
	if ULSS_IMPEGNATIVA_OLD='110' THEN
		ULSS_IMPEGNATIVA_NEW=504;

	*;
	if ULSS_IMPEGNATIVA_OLD='118' THEN
		ULSS_IMPEGNATIVA_NEW=505;

	if ULSS_IMPEGNATIVA_OLD='119' THEN
		ULSS_IMPEGNATIVA_NEW=505;

	*;
	if ULSS_IMPEGNATIVA_OLD='115' THEN
		ULSS_IMPEGNATIVA_NEW=506;

	if ULSS_IMPEGNATIVA_OLD='116' THEN
		ULSS_IMPEGNATIVA_NEW=506;

	if ULSS_IMPEGNATIVA_OLD='117' THEN
		ULSS_IMPEGNATIVA_NEW=506;

	*;
	if ULSS_IMPEGNATIVA_OLD='103' THEN
		ULSS_IMPEGNATIVA_NEW=507;

	if ULSS_IMPEGNATIVA_OLD='104' THEN
		ULSS_IMPEGNATIVA_NEW=507;

	*;
	if ULSS_IMPEGNATIVA_OLD='106' THEN
		ULSS_IMPEGNATIVA_NEW=508;

	if ULSS_IMPEGNATIVA_OLD='105' THEN
		ULSS_IMPEGNATIVA_NEW=508;

	*;
	if ULSS_IMPEGNATIVA_OLD='120' THEN
		ULSS_IMPEGNATIVA_NEW=509;

	if ULSS_IMPEGNATIVA_OLD='121' THEN
		ULSS_IMPEGNATIVA_NEW=509;

	if ULSS_IMPEGNATIVA_OLD='122' THEN
		ULSS_IMPEGNATIVA_NEW=509;
RUN;


DATA AU;
	SET AU;
	ANNO_PRIMO_INGRESSO=YEAR(DATARIC_STRUTTURA);
	ANNO_INGRESSO_UDO=YEAR(DATARIC_UDO);
	ANNO_DIMISSIONE=YEAR(DATADIM_UDO);
RUN;

/*RICREO LE DATE PER IL CONTEGGIO DEI GIORNI LORDI DI PERMANENZA*/
DATA AU;
	SET AU;

	IF ANNO_INGRESSO_UDO<&anno THEN
		DATARIC_UDO_NEW=mdy(01,01,&anno);

	IF ANNO_INGRESSO_UDO=&anno THEN
		DATARIC_UDO_NEW=DATARIC_UDO;

	IF DATADIM_UDO=. or ANNO_DIMISSIONE=(&anno+1) THEN
		DATADIM_UDO_NEW=mdy(12,31,&anno);

	IF ANNO_DIMISSIONE=&anno THEN
		DATADIM_UDO_NEW=DATADIM_UDO;
	FORMAT DATADIM_UDO_NEW DATARIC_UDO_NEW DATE9.;
RUN;


DATA AU;
	SET AU;
	GIORNI_LORDI_&anno = (DATADIM_UDO_NEW - DATARIC_UDO_NEW) +1;
RUN;

DATA AU;
	SET AU;

	IF GIORNI_LORDI_&anno = 366 THEN
		GIORNI_LORDI = 365;
	ELSE GIORNI_LORDI = GIORNI_LORDI_&anno;
RUN;


DATA AU;
	SET AU;
	VAL_SAN_LORDO 				= GIORNI_LORDI * VALORE_QUOTA_RILIEVO_num;
	VAL_EC_SOCIALE_LORDO 		= GIORNI_LORDI * TOTALE_QUOTA_GIORNALIERA_num;
	VAL_EC_ALBERGHIERO_LORDO 	= GIORNI_LORDI * COMPONENTE_SANITARIA_QUOTA_num;
	UT_EQ_LORDO					= GIORNI_LORDI/365;
RUN;
/*FARE LA CHIAVE CODICE_SOGGETTO_BIN+COD_UDO*/
DATA AU; SET AU; 
KEY_SOGGETTO_PER_UDO=CATS(CODICE_SOGGETTO_BIN,COD_UDO);
RUN; 




/**************************/
/*IMPORTO IL TRACCIATO DELLE ASSENZE*/
/*FARE LA CHIAVE CODICE_SOGGETTO_BIN+COD_UDO*/


data assenze_OSPEDALIERI;
	set ASSENZE; WHERE COD_MOTIVAZIONE_ASSENZA='1'; 
run; /*12963*/

/*GIORNI DI ASSENZA LORDI PER POSIZIONE*/
data assenze_OSPEDALIERI;
	set assenze_OSPEDALIERI;
	if (DATA_FI_ASSENZA_TEMP ne . and DATA_IN_ASSENZA_TEMP ne .) then
		giorni_assenza_lordi = (DATA_FI_ASSENZA_TEMP - DATA_IN_ASSENZA_TEMP)+1;
run;

/*ATTACCO AL TRACCIATO 7*/
proc sort data=assenze_OSPEDALIERI;
	by cod_udo;
run;

proc sort data=udo;
	by cod_udo;
run;

DATA ASSENZE_UDO;/**/
	MERGE assenze_OSPEDALIERI (IN=A) UDO (IN=B);
	BY cod_udo;
	IF A;
RUN;

/*CREO UN DB CON LA CONTA DEI GIORNI DI ASSENZA PER CODICE_SOGGETTO_BIN+COD_UDO*/
DATA ASSENZE_UDO; SET ASSENZE_UDO; 
KEY_SOGGETTO_PER_UDO=CATS(CODICE_SOGGETTO_BIN,COD_UDO);
RUN; 

PROC SQL;
	create table ASSENZE_PER_KEY
		as SELECT DISTINCT  KEY_SOGGETTO_PER_UDO, 
			SUM(giorni_assenza_lordi) AS SUM_giorni_assenza_lordi
		FROM ASSENZE_UDO GROUP BY KEY_SOGGETTO_PER_UDO;
QUIT;/**/

/*UNISCO ADT E ASSENZE PER KEY_SOGGETTO_PER_UDO*/
proc sort data=AU;
	by KEY_SOGGETTO_PER_UDO;
run;

proc sort data=ASSENZE_PER_KEY;
	by KEY_SOGGETTO_PER_UDO;
run;

DATA AU_ASSENZE;/**/
	MERGE AU (IN=A) ASSENZE_PER_KEY (IN=B);
	BY KEY_SOGGETTO_PER_UDO;
	IF A;
RUN;

proc sort data=AU_ASSENZE;
	by CODICE_SOGGETTO_BIN;
run;

DATA AU_ASSENZE; SET AU_ASSENZE;
GIORNI_NETTI= GIORNI_LORDI-SUM_giorni_assenza_lordi;
RUN; 

DATA AU_ASSENZE; SET AU_ASSENZE;
IF GIORNI_NETTI<0 THEN GIORNI_NETTI=0; 
if sum_giorni_assenza_lordi =. then giorni_netti= giorni_lordi; 
RUN; 
/*+++++*/

/*ATTACCO LE SDO
/*da rivedere con nuova tabella */*/
/*++++*/
proc sql;
	create table SDO as
		select *
			from DWHBT.BTDETT_SDO_DIMISSIONI
				where  ANNO="&anno."  ;
quit;

DATA SDO;
	SET SDO;
	RENAME CODICE_SOGGETTO = CODICE_SOGGETTO_BIN;
	DATA_RIC_NEW=DATEPART(DATA_RICOVERO);
	DATA_DIM_NEW=DATEPART(DATA_DIMISS);
	FORMAT DATA_RIC_NEW DATA_DIM_NEW DATE9.;
RUN;

DATA SDO1;
	SET SDO;
	KEEP 
	CODICE_SOGGETTO_BIN  
	DATA_RIC_NEW
	DATA_DIM_NEW;
RUN;

DATA ASSENZE_PER_SDO;
SET ASSENZE_UDO;
KEEP
DATA_IN_ASSENZA_TEMP
DATA_FI_ASSENZA_TEMP
CODICE_SOGGETTO_BIN
GIORNI_ASSENZA_LORDI
;
WHERE COD_MOTIVAZIONE_ASSENZA='1';
RUN;


proc sort data=ASSENZE_PER_SDO;
	by CODICE_SOGGETTO_BIN data_in_assenza_temp;
run;

proc sort data=SDO1;
	by CODICE_SOGGETTO_BIN DATA_RIC_NEW;
run;

DATA P;/**/
	MERGE ASSENZE_PER_SDO (IN=A) SDO1 (IN=B);
	BY CODICE_SOGGETTO_BIN;
	IF A;

RUN;
/*controllo per vedere se le date sono attendibili (lasco di una settimana)*/
DATA P;
	SET P;

	IF -3 <= (DATA_IN_ASSENZA_TEMP - DATA_RIC_NEW) <= 3 THEN
		CONTROLLO_DATA_IN_UDO=1;
	ELSE CONTROLLO_DATA_IN_UDO=0;

	IF -3 <= (DATA_FI_ASSENZA_TEMP - DATA_DIM_NEW) <= 3 THEN
		CONTROLLO_DATA_OUT_UDO=1;
RUN;

data p; set P;
if DATA_RIC_NEW ne . then presente_in_sdo=1; else presente_in_sdo=0;
run;

data p; 
set p ;
keep codice_soggetto_bin presente_in_sdo;
run; 


/*attacco con au_assenze*/

proc sort data=AU_ASSENZE;
	by CODICE_SOGGETTO_BIN;
run;

proc sort data=p;
	by CODICE_SOGGETTO_BIN;
run;

DATA AU_ASSENZE_SDO;/**/
	MERGE AU_ASSENZE (IN=A) P (IN=B);
	BY CODICE_SOGGETTO_BIN;
	IF A;

RUN;

/*COSTRUISCO UNA CHIAVE PER CODICE_SOGGETTO_BIN+ID_EPISODIO
TOLGO I DUPLICATI PER QUESTA CHIAVE*/
DATA AU_ASSENZE_SDO;
SET AU_ASSENZE_SDO;
k7=CATS(CODICE_SOGGETTO_BIN,ID_EPISODIO);
RUN;

proc sort nodupkey data=au_assenze_sdo out=AU_ASSENZE_SDO_UNICI; by k7; run; 



proc sort data=AU_ASSENZE_SDO_UNICI;
	by CODICE_SOGGETTO_BIN;
run;

proc sort data=ana;
	by CODICE_SOGGETTO_BIN;
run;

DATA AU_ASSENZE_SDO_UNICI1;/**/
	MERGE AU_ASSENZE_SDO_UNICI (IN=A) ana (IN=B);
	BY CODICE_SOGGETTO_BIN;
	IF A;
RUN;


/*CREO LA TABELLA ARCIPELAGO TER*/
DATA ARCIPELAGO5_TER;
	SET AU_ASSENZE_SDO_UNICI1;
	KEEP
	CODICE_SOGGETTO_BIN
		KEY_SOGGETTO_PER_UDO
		ULSS_UDO
		ULSS_UDO_NEW
		ANNO
		COD_UDO
		TIPO_UDO
		REG_ENTE_GES
		REG_PROVV_CDS
		GIORNI_LORDI
		SUM_giorni_assenza_lordi
		GIORNI_NETTI
		CLETA
		SESSO
		presente_in_sdo
	;
RUN;


DATA ARCIPELAGO5_TER;
	retain
		CODICE_SOGGETTO_BIN
		KEY_SOGGETTO_PER_UDO
		ULSS_UDO
		ULSS_UDO_NEW
		ANNO
		COD_UDO
		TIPO_UDO
		REG_ENTE_GES
		REG_PROVV_CDS
		GIORNI_LORDI
		SUM_giorni_assenza_lordi
		GIORNI_NETTI
		CLETA
		SESSO
		presente_in_sdo;
	set ARCIPELAGO5_TER;
RUN;


DATA ARCIPELAGO5_TER;set arcipelago5_ter; 
if codice_soggetto_bin = '' then delete; run; 

%mend; 

%SET_ANAGRAFICA_FAR;
%set_adt_far;
%set_udo;
%set_assenze;
%TABELLA_005_ter;

/*esecuzione delle macro
QUI OCCHIO CHE C'è la vista sulle SDO,
quindi controllare prima se c'è il dato sulla vista 
delle sdo
DWHBT.BTDETT_SDO_DIMISSIONI 
*/
%let anno=2016; 	/*anno di interesse*/
%let fase=12; 		/*fase di interesse*/

/*non ci sono le SDO 2017 quindi non va*/
/*PER ACCODAMENTO DI PIù ANNI*/
/*DATA TMP_2016; SET ARCIPELAGO5_TER; RUN; /*ANNO 2016*/

/*DATA TMP_2017; SET ARCIPELAGO5_TER; RUN; *//*ANNO 2017*/

/*DATA ARCIPELAGO_005_TER; SET TMP_2016 TMP_2017; RUN; 

