/*************************************************	*/
/***********************************************	*/
/*				TABELLA ARCIPELAGO 12				*/
/*********************************************	*****/
/*********************************************	*****/
/**/

LIBNAME FAR_2016 '/sasprd/staging/staging_san1/S1_ORPSS/config/FAR_2016';
LIBNAME FAR_2017 '/sasprd/staging/staging_san1/S1_ORPSS/config/FAR_2017';
%include '/sasprd/staging/staging_san1/S1_ORPSS/config/MACRO_ORPSS/far_udo_atti.sas' ;

%set_udo; 


%macro set_cds;
proc sql;
	create table cds as
		select *
			from DWHODD.ODD_FAR_UNI_B0_IMPORT
				where (anno=&anno  and flg_err=0 and fase=&fase_cds);/*lascio sempre a 0*/
quit;/**/


data cds;
	set cds;
	rename COD_STRUT_EROG_UDO=COD_UDO;
run;


/*cast a numero delle variabili quantitative*/
DATA cds;
	SET cds;
	HH_SER_COORD_PD_NUM=INPUT(HH_SER_COORD_PD,BEST12.);
	HH_SER_OSS_PD_NUM=INPUT(HH_SER_OSS_PD,BEST12.);
	HH_SER_OSS_S_PD_NUM=INPUT(HH_SER_OSS_S_PD,BEST12.);
	HH_SER_INFER_PD_NUM=INPUT(HH_SER_INFER_PD,BEST12.);
	HH_SER_ASS_SOC_PD_NUM=INPUT(HH_SER_ASS_SOC_PD,BEST12.);
	HH_SER_EDU_PD_NUM=INPUT(HH_SER_EDU_PD,BEST12.);
	HH_SER_PSI_PD_NUM=INPUT(HH_SER_PSI_PD,BEST12.);
	HH_SER_MED_PD_NUM=INPUT(HH_SER_MED_PD,BEST12.);
	HH_SER_FISIAT_PD_NUM=INPUT(HH_SER_FISIAT_PD,BEST12.);
	HH_SER_FISIOT_PD_NUM=INPUT(HH_SER_FISIOT_PD,BEST12.);
	HH_FOR_COORD_PD_NUM=INPUT(HH_FOR_COORD_PD,BEST12.);
	HH_FOR_OSS_PD_NUM=INPUT(HH_FOR_OSS_PD,BEST12.);
	HH_FOR_OSS_S_PD_NUM=INPUT(HH_FOR_OSS_S_PD,BEST12.);
	HH_FOR_INFER_PD_NUM=INPUT(HH_FOR_INFER_PD,BEST12.);
	HH_FOR_ASS_SOC_PD_NUM=INPUT(HH_FOR_ASS_SOC_PD,BEST12.);
	HH_FOR_EDU_PD_NUM=INPUT(HH_FOR_EDU_PD,BEST12.);
	HH_FOR_PSI_PD_NUM=INPUT(HH_FOR_PSI_PD,BEST12.);
	HH_FOR_MED_PD_NUM=INPUT(HH_FOR_MED_PD,BEST12.);
	HH_FOR_FISIAT_PD_NUM=INPUT(HH_FOR_FISIAT_PD,BEST12.);
	HH_FOR_FISIOT_PD_NUM=INPUT(HH_FOR_FISIOT_PD,BEST12.);
	GG_MATERNITA_PD_NUM=INPUT(GG_MATERNITA_PD,BEST12.);
	HH_PULIZIE_PD_NUM=INPUT(HH_PULIZIE_PD,BEST12.);
	GG_MALATTIA_PD_NUM=INPUT(GG_MALATTIA_PD,BEST12.);
	HH_SER_COORD_PND_NUM=INPUT(HH_SER_COORD_PND,BEST12.);
	HH_SER_OSS_PND_NUM=INPUT(HH_SER_OSS_PND,BEST12.);
	HH_SER_OSS_S_PND_NUM=INPUT(HH_SER_OSS_S_PND,BEST12.);
	HH_SER_INFER_PND_NUM=INPUT(HH_SER_INFER_PND,BEST12.);
	HH_SER_ASS_SOC_PND_NUM=INPUT(HH_SER_ASS_SOC_PND,BEST12.);
	HH_SER_EDU_PND_NUM=INPUT(HH_SER_EDU_PND,BEST12.);
	HH_SER_PSI_PND_NUM=INPUT(HH_SER_PSI_PND,BEST12.);
	HH_SER_MED_PND_NUM=INPUT(HH_SER_MED_PND,BEST12.);
	HH_SER_FISIAT_PND_NUM=INPUT(HH_SER_FISIAT_PND,BEST12.);
	HH_SER_FISIOT_PND_NUM=INPUT(HH_SER_FISIOT_PND,BEST12.);
	HH_FOR_COORD_PND_NUM=INPUT(HH_FOR_COORD_PND,BEST12.);
	HH_FOR_OSS_PND_NUM=INPUT(HH_FOR_OSS_PND,BEST12.);
	HH_FOR_OSS_S_PND_NUM=INPUT(HH_FOR_OSS_S_PND,BEST12.);
	HH_FOR_INFER_PND_NUM=INPUT(HH_FOR_INFER_PND,BEST12.);
	HH_FOR_ASS_SOC_PND_NUM=INPUT(HH_FOR_ASS_SOC_PND,BEST12.);
	HH_FOR_EDU_PND_NUM=INPUT(HH_FOR_EDU_PND,BEST12.);
	HH_FOR_PSI_PND_NUM=INPUT(HH_FOR_PSI_PND,BEST12.);
	HH_FOR_MED_PND_NUM=INPUT(HH_FOR_MED_PND,BEST12.);
	HH_FOR_FISIAT_PND_NUM=INPUT(HH_FOR_FISIAT_PND,BEST12.);
	HH_FOR_FISIOT_PND_NUM=INPUT(HH_FOR_FISIOT_PND,BEST12.);
	HH_ASS_DIR_PER_VOL_NUM=INPUT(HH_ASS_DIR_PER_VOL,BEST12.);
	GG_APERTURA_CD_NUM=INPUT(GG_APERTURA_CD,BEST12.);
	HH_APERTURA_CD_NUM=INPUT(HH_APERTURA_CD,BEST12.);
RUN;

DATA cds;
	SET cds;
	COSTO_COORD_PD_NUM=INPUT(COSTO_COORD_PD,BEST12.);
	COSTO_OSS_PD_NUM=INPUT(COSTO_OSS_PD,BEST12.);
	COSTO_OSS_S_PD_NUM=INPUT(COSTO_OSS_S_PD,BEST12.);
	COSTO_INFER_PD_NUM=INPUT(COSTO_INFER_PD,BEST12.);
	COSTO_ASS_SOC_PD_NUM=INPUT(COSTO_ASS_SOC_PD,BEST12.);
	COSTO_EDU_PD_NUM=INPUT(COSTO_EDU_PD,BEST12.);
	COSTO_PSI_PD_NUM=INPUT(COSTO_PSI_PD,BEST12.);
	COSTO_MED_PD_NUM=INPUT(COSTO_MED_PD,BEST12.);
	COSTO_FISIAT_PD_NUM=INPUT(COSTO_FISIAT_PD,BEST12.);
	COSTO_FISIOT_PD_NUM=INPUT(COSTO_FISIOT_PD,BEST12.);
	COSTO_MATERNITA_PD_NUM=INPUT(COSTO_MATERNITA_PD,BEST12.);
	COSTO_MALATTIA_PD_NUM=INPUT(COSTO_MALATTIA_PD,BEST12.);
	COSTO_COORD_PND_NUM=INPUT(COSTO_COORD_PND,BEST12.);
	COSTO_OSS_PND_NUM=INPUT(COSTO_OSS_PND,BEST12.);
	COSTO_OSS_S_PND_NUM=INPUT(COSTO_OSS_S_PND,BEST12.);
	COSTO_INFER_PND_NUM=INPUT(COSTO_INFER_PND,BEST12.);
	COSTO_ASS_SOC_PND_NUM=INPUT(COSTO_ASS_SOC_PND,BEST12.);
	COSTO_EDU_PND_NUM=INPUT(COSTO_EDU_PND,BEST12.);
	COSTO_PSI_PND_NUM=INPUT(COSTO_PSI_PND,BEST12.);
	COSTO_MED_PND_NUM=INPUT(COSTO_MED_PND,BEST12.);
	COSTO_FISIAT_PND_NUM=INPUT(COSTO_FISIAT_PND,BEST12.);
	COSTO_FISIOT_PND_NUM=INPUT(COSTO_FISIOT_PND,BEST12.);
	COSTO_AUS_INCONT_NUM=INPUT(COSTO_AUS_INCONT,BEST12.);
	COSTO_AUS_ALTRO_NUM=INPUT(COSTO_AUS_ALTRO,BEST12.);
RUN;

DATA cds;
	SET cds;
	drop 
		HH_SER_COORD_PD
		HH_SER_OSS_PD
		HH_SER_OSS_S_PD
		HH_SER_INFER_PD
		HH_SER_ASS_SOC_PD
		HH_SER_EDU_PD
		HH_SER_PSI_PD
		HH_SER_MED_PD
		HH_SER_FISIAT_PD
		HH_SER_FISIOT_PD
		COSTO_COORD_PD
		COSTO_OSS_PD
		COSTO_OSS_S_PD
		COSTO_INFER_PD
		COSTO_ASS_SOC_PD
		COSTO_EDU_PD
		COSTO_PSI_PD
		COSTO_MED_PD
		COSTO_FISIAT_PD
		COSTO_FISIOT_PD
		HH_FOR_COORD_PD
		HH_FOR_OSS_PD
		HH_FOR_OSS_S_PD
		HH_FOR_INFER_PD
		HH_FOR_ASS_SOC_PD
		HH_FOR_EDU_PD
		HH_FOR_PSI_PD
		HH_FOR_MED_PD
		HH_FOR_FISIAT_PD
		HH_FOR_FISIOT_PD
		GG_MATERNITA_PD
		COSTO_MATERNITA_PD
		HH_PULIZIE_PD
		GG_MALATTIA_PD
		COSTO_MALATTIA_PD
		HH_SER_COORD_PND
		HH_SER_OSS_PND
		HH_SER_OSS_S_PND
		HH_SER_INFER_PND
		HH_SER_ASS_SOC_PND
		HH_SER_EDU_PND
		HH_SER_PSI_PND
		HH_SER_MED_PND
		HH_SER_FISIAT_PND
		HH_SER_FISIOT_PND
		COSTO_COORD_PND
		COSTO_OSS_PND
		COSTO_OSS_S_PND
		COSTO_INFER_PND
		COSTO_ASS_SOC_PND
		COSTO_EDU_PND
		COSTO_PSI_PND
		COSTO_MED_PND
		COSTO_FISIAT_PND
		COSTO_FISIOT_PND
		HH_FOR_COORD_PND
		HH_FOR_OSS_PND
		HH_FOR_OSS_S_PND
		HH_FOR_INFER_PND
		HH_FOR_ASS_SOC_PND
		HH_FOR_EDU_PND
		HH_FOR_PSI_PND
		HH_FOR_MED_PND
		HH_FOR_FISIAT_PND
		HH_FOR_FISIOT_PND
		COSTO_AUS_INCONT
		COSTO_AUS_ALTRO
		HH_ASS_DIR_PER_VOL
		GG_APERTURA_CD
		HH_APERTURA_CD;
RUN;
%mend; 



/*costo orario per figura professionale
/*CDS*/

%macro tabella_012; 


PROC SORT DATA=cds;
	BY cod_udo;
RUN;

PROC SORT DATA=udo;
	BY cod_udo;
RUN;

data CDS_UDO;
	MERGE CDS (in=a) udo (in=b);
	BY COD_UDO;
	if a AND B ;
RUN;
data CDS_UDO;
	set CDS_UDO;

	if ULSS_UDO='101' THEN
		ULSS_UDO_NEW=501;

	if ULSS_UDO='102' THEN
		ULSS_UDO_NEW=501;

	*;
	if ULSS_UDO='109' THEN
		ULSS_UDO_NEW=502;

	if ULSS_UDO='107' THEN
		ULSS_UDO_NEW=502;

	if ULSS_UDO='108' THEN
		ULSS_UDO_NEW=502;

	*;
	if ULSS_UDO='112' THEN
		ULSS_UDO_NEW=503;

	if ULSS_UDO='113' THEN
		ULSS_UDO_NEW=503;

	if ULSS_UDO='114' THEN
		ULSS_UDO_NEW=503;

	*;
	if ULSS_UDO='110' THEN
		ULSS_UDO_NEW=504;

	*;
	if ULSS_UDO='118' THEN
		ULSS_UDO_NEW=505;

	if ULSS_UDO='119' THEN
		ULSS_UDO_NEW=505;

	*;
	if ULSS_UDO='115' THEN
		ULSS_UDO_NEW=506;

	if ULSS_UDO='116' THEN
		ULSS_UDO_NEW=506;

	if ULSS_UDO='117' THEN
		ULSS_UDO_NEW=506;

	*;
	if ULSS_UDO='103' THEN
		ULSS_UDO_NEW=507;

	if ULSS_UDO='104' THEN
		ULSS_UDO_NEW=507;

	*;
	if ULSS_UDO='106' THEN
		ULSS_UDO_NEW=508;

	if ULSS_UDO='105' THEN
		ULSS_UDO_NEW=508;

	*;
	if ULSS_UDO='120' THEN
		ULSS_UDO_NEW=509;

	if ULSS_UDO='121' THEN
		ULSS_UDO_NEW=509;

	if ULSS_UDO='122' THEN
		ULSS_UDO_NEW=509;


	if ULSS_UDO='501' then ULSS_UDO_NEW='501';
if ULSS_UDO='502' then ULSS_UDO_NEW='502';
if ULSS_UDO='503' then ULSS_UDO_NEW='503';
if ULSS_UDO='504' then ULSS_UDO_NEW='504';
if ULSS_UDO='505' then ULSS_UDO_NEW='505';
if ULSS_UDO='506' then ULSS_UDO_NEW='506';
if ULSS_UDO='507' then ULSS_UDO_NEW='507';
if ULSS_UDO='508' then ULSS_UDO_NEW='508';
if ULSS_UDO='509' then ULSS_UDO_NEW='509';
RUN;


/*SOMMA ORE E COSTI PERSONALE DIPENDENTE E NON DIPENDENTE*/
DATA cds_udo;
	SET cds_udo;
	HH_SER_COORD=(HH_SER_COORD_PD_num+HH_SER_COORD_PND_num);
	HH_SER_OSS=(HH_SER_OSS_PD_num+HH_SER_OSS_PND_num);
	HH_SER_OSS_S=(HH_SER_OSS_S_PD_num+HH_SER_OSS_S_PND_num);
	HH_SER_OSS_TOTALE= (HH_SER_OSS_PD_num+HH_SER_OSS_PND_num+HH_SER_OSS_S_PD_num+HH_SER_OSS_S_PND_num);
	HH_SER_INFER=(HH_SER_INFER_PD_num+HH_SER_INFER_PND_num);
	HH_SER_ASS_SOC=(HH_SER_ASS_SOC_PD_num+HH_SER_ASS_SOC_PND_num);
	HH_SER_EDU=(HH_SER_EDU_PD_num+HH_SER_EDU_PND_num);
	HH_SER_PSI=(HH_SER_PSI_PD_num+HH_SER_PSI_PND_num);
	HH_SER_MED=(HH_SER_MED_PD_num+HH_SER_MED_PND_num);
	HH_SER_FISIAT=(HH_SER_FISIAT_PD_num+HH_SER_FISIAT_PND_num);
	HH_SER_FISIOT=(HH_SER_FISIOT_PD_num+HH_SER_FISIOT_PND_num);
	HH_FOR_COORD=(HH_FOR_COORD_PD_num+HH_FOR_COORD_PND_num);
	HH_FOR_OSS=(HH_FOR_OSS_PD_num+HH_FOR_OSS_PND_num);
	HH_FOR_OSS_S=(HH_FOR_OSS_S_PD_num+HH_FOR_OSS_S_PND_num);
	HH_FOR_OSS_TOTALE=(HH_FOR_OSS_PD_num+HH_FOR_OSS_PND_num+HH_FOR_OSS_S_PD_num+HH_FOR_OSS_S_PND_num);
	HH_FOR_INFER=(HH_FOR_INFER_PD_num+HH_FOR_INFER_PND_num);
	HH_FOR_ASS_SOC=(HH_FOR_ASS_SOC_PD_num+HH_FOR_ASS_SOC_PND_num);
	HH_FOR_EDU=(HH_FOR_EDU_PD_num+HH_FOR_EDU_PND_num);
	HH_FOR_PSI=(HH_FOR_PSI_PD_num+HH_FOR_PSI_PND_num);
	HH_FOR_MED=(HH_FOR_MED_PD_num+HH_FOR_MED_PND_num);
	HH_FOR_FISIAT=(HH_FOR_FISIAT_PD_num+HH_FOR_FISIAT_PND_num);
	HH_FOR_FISIOT=(HH_FOR_FISIOT_PD_num+HH_FOR_FISIOT_PND_num);
run; 

DATA cds_udo;
	SET cds_udo;
	COSTO_COORD = COSTO_COORD_PD_NUM+COSTO_COORD_PND_NUM;
	COSTO_OSS = COSTO_OSS_PD_NUM+COSTO_OSS_PND_NUM;
	COSTO_OSS_S = COSTO_OSS_S_PD_NUM+COSTO_OSS_S_PND_NUM;
	COSTO_OSS_TOTALE = COSTO_OSS_PD_NUM+COSTO_OSS_PND_NUM + COSTO_OSS_S_PD_NUM+COSTO_OSS_S_PND_NUM; 
	COSTO_INFER = COSTO_INFER_PD_NUM+COSTO_INFER_PND_NUM;
	COSTO_ASS_SOC = COSTO_ASS_SOC_PD_NUM+COSTO_ASS_SOC_PND_NUM;
	COSTO_EDU = COSTO_EDU_PD_NUM+COSTO_EDU_PND_NUM;
	COSTO_PSI = COSTO_PSI_PD_NUM+COSTO_PSI_PND_NUM;
	COSTO_MED = COSTO_MED_PD_NUM+COSTO_MED_PND_NUM;
	COSTO_FISIAT = COSTO_FISIAT_PD_NUM+COSTO_FISIAT_PND_NUM;
	COSTO_FISIOT = COSTO_FISIOT_PD_NUM+COSTO_FISIOT_PND_NUM;
run;

/*CALCOLO "INCIDENZA FORMAZIONE" sulle ore di servizio*/

DATA cds_udo;
	SET cds_udo;
	if HH_SER_COORD ne 0 then INCIDENZA_FOR_COORD = (HH_FOR_COORD/HH_SER_COORD)*100;
	if HH_SER_COORD = 0 then INCIDENZA_FOR_COORD = 0;
	if HH_SER_OSS_TOTALE ne 0 then INCIDENZA_FOR_OSS = (HH_FOR_OSS_TOTALE/HH_SER_OSS_TOTALE)*100;
	if HH_SER_OSS_TOTALE = 0 then INCIDENZA_FOR_OSS = 0;
	if HH_SER_INFER ne 0 then INCIDENZA_FOR_INF = (HH_FOR_INFER/HH_SER_INFER)*100;
	if HH_SER_INFER = 0 then INCIDENZA_FOR_INF = 0; 
	if HH_SER_ASS_SOC ne 0 then  INCIDENZA_FOR_ASS_SOC 	= (HH_FOR_ASS_SOC/HH_SER_ASS_SOC)*100;
	if HH_SER_ASS_SOC = 0 then INCIDENZA_FOR_ASS_SOC = 0;
	if HH_SER_EDU ne 0 then INCIDENZA_FOR_EDU = (HH_FOR_EDU/HH_SER_EDU)*100;
	if HH_SER_EDU = 0 then INCIDENZA_FOR_EDU = 0;
	if HH_SER_PSI ne 0 then INCIDENZA_FOR_PSI = (HH_FOR_PSI/HH_SER_PSI)*100;
	if HH_SER_PSI = 0 then INCIDENZA_FOR_PSI = 0; 
	if HH_SER_MED ne 0 then INCIDENZA_FOR_MED = (HH_FOR_MED/HH_SER_MED)*100;
	if HH_SER_MED = 0 then INCIDENZA_FOR_MED = 0;
	if HH_SER_FISIAT ne 0 then INCIDENZA_FOR_FISIAT = (HH_FOR_FISIAT/HH_SER_FISIAT)*100;
	if HH_SER_FISIAT = 0 then INCIDENZA_FOR_FISIAT = 0;
	if HH_SER_FISIOT ne 0 then INCIDENZA_FOR_FISIOT = (HH_FOR_FISIOT/HH_SER_FISIOT)*100;
	if HH_SER_FISIOT = 0 then INCIDENZA_FOR_FISIOT = 0;
run;
/*CALCOLO COSTO ORARIO*/
/* */
/*++++*/

DATA CDS_UDO; SET CDS_UDO; 
ORE_COORD=HH_SER_COORD+HH_FOR_COORD;
ORE_OSS=HH_SER_OSS_TOTALE+HH_FOR_OSS_TOTALE;
ORE_INFER=HH_SER_INFER+HH_FOR_INFER;
ORE_ASS_SOC=HH_SER_ASS_SOC+HH_FOR_ASS_SOC;
ORE_EDU=HH_SER_EDU+HH_FOR_EDU;
ORE_PSI=HH_SER_PSI+HH_FOR_PSI;
ORE_MED=HH_SER_MED+HH_FOR_MED;
ORE_FISIAT=HH_SER_FISIAT+HH_FOR_FISIAT;
ORE_FISIOT=HH_SER_FISIOT+HH_FOR_FISIOT;
RUN;


DATA CDS_UDO;
SET CDS_UDO;
IF ORE_COORD NE 0 THEN COSTO_ORARIO_COORD = COSTO_COORD/(HH_SER_COORD+HH_FOR_COORD);
IF ORE_COORD = 0 THEN COSTO_ORARIO_COORD = 0;
IF ORE_OSS NE 0 THEN COSTO_ORARIO_OSS = COSTO_OSS_TOTALE/(HH_SER_OSS_TOTALE+HH_FOR_OSS_TOTALE);
IF ORE_OSS = 0 THEN COSTO_ORARIO_OSS = 0;
IF ORE_INFER NE 0 THEN COSTO_ORARIO_INFER = COSTO_INFER/(HH_SER_INFER+HH_FOR_INFER);
IF ORE_INFER =0 THEN COSTO_ORARIO_INFER = 0;
IF ORE_ASS_SOC NE 0 THEN COSTO_ORARIO_ASS_SOC = COSTO_ASS_SOC/(HH_SER_ASS_SOC+HH_FOR_ASS_SOC);
IF ORE_ASS_SOC = 0 THEN COSTO_ORARIO_ASS_SOC = 0; 
IF ORE_EDU NE 0 THEN COSTO_ORARIO_EDU = COSTO_EDU/(HH_SER_EDU+HH_FOR_EDU);
IF ORE_EDU = 0 THEN COSTO_ORARIO_EDU =0;
IF ORE_PSI NE 0 THEN COSTO_ORARIO_PSI = COSTO_PSI/(HH_SER_PSI+HH_FOR_PSI);
IF ORE_PSI = 0 THEN COSTO_ORARIO_PSI = 0;
IF ORE_MED NE 0 THEN COSTO_ORARIO_MED = COSTO_MED/(HH_SER_MED+HH_FOR_MED);
IF ORE_MED = 0 THEN COSTO_ORARIO_MED = 0;
IF ORE_FISIAT NE 0 THEN COSTO_ORARIO_FISIAT = COSTO_FISIAT/(HH_SER_FISIAT+HH_FOR_FISIAT);
IF ORE_FISIAT = 0 THEN  COSTO_ORARIO_FISIAT = 0 ;
IF ORE_FISIOT NE 0 THEN COSTO_ORARIO_FISIOT = COSTO_FISIOT/(HH_SER_FISIOT+HH_FOR_FISIOT);
IF ORE_FISIOT = 0 THEN COSTO_ORARIO_FISIOT = 0 ; 
RUN; 

DATA CDS_UDO; SET CDS_UDO; 
IF GG_APERTURA_CD_NUM EQ . THEN GG_APERTURA_CD_NUM=0;
IF HH_APERTURA_CD_NUM EQ . THEN HH_APERTURA_CD_NUM=0;
RUN;  

DATA CDS_UDO;
SET CDS_UDO;
rename indirizzo_3=natura_giuridica; 
run; 

DATA CDS_UDO;
SET CDS_UDO;
KEEP
ULSS_UDO
ULSS_UDO_NEW
ANNO_RILEVAZIONE
COD_UDO
REG_PROVV_CDS
REG_ENTE_GES
/*5.5-5.72*/
HH_SER_COORD_PD_NUM
HH_SER_OSS_PD_NUM
HH_SER_OSS_S_PD_NUM
HH_SER_INFER_PD_NUM
HH_SER_ASS_SOC_PD_NUM
HH_SER_EDU_PD_NUM
HH_SER_PSI_PD_NUM
HH_SER_MED_PD_NUM
HH_SER_FISIAT_PD_NUM
HH_SER_FISIOT_PD_NUM
COSTO_COORD_PD_NUM
COSTO_OSS_PD_NUM
COSTO_OSS_S_PD_NUM
COSTO_INFER_PD_NUM
COSTO_ASS_SOC_PD_NUM
COSTO_EDU_PD_NUM
COSTO_PSI_PD_NUM
COSTO_MED_PD_NUM
COSTO_FISIAT_PD_NUM
COSTO_FISIOT_PD_NUM
HH_FOR_COORD_PD_NUM
HH_FOR_OSS_PD_NUM
HH_FOR_OSS_S_PD_NUM
HH_FOR_INFER_PD_NUM
HH_FOR_ASS_SOC_PD_NUM
HH_FOR_EDU_PD_NUM
HH_FOR_PSI_PD_NUM
HH_FOR_MED_PD_NUM
HH_FOR_FISIAT_PD_NUM
HH_FOR_FISIOT_PD_NUM
GG_MATERNITA_PD_NUM
COSTO_MATERNITA_PD_NUM
HH_PULIZIE_PD_NUM
GG_MALATTIA_PD_NUM
COSTO_MALATTIA_PD_NUM
HH_SER_COORD_PND_NUM
HH_SER_OSS_PND_NUM
HH_SER_OSS_S_PND_NUM
HH_SER_INFER_PND_NUM
HH_SER_ASS_SOC_PND_NUM
HH_SER_EDU_PND_NUM
HH_SER_PSI_PND_NUM
HH_SER_MED_PND_NUM
HH_SER_FISIAT_PND_NUM
HH_SER_FISIOT_PND_NUM
COSTO_COORD_PND_NUM
COSTO_OSS_PND_NUM
COSTO_OSS_S_PND_NUM
COSTO_INFER_PND_NUM
COSTO_ASS_SOC_PND_NUM
COSTO_EDU_PND_NUM
COSTO_PSI_PND_NUM
COSTO_MED_PND_NUM
COSTO_FISIAT_PND_NUM
COSTO_FISIOT_PND_NUM
HH_FOR_COORD_PND_NUM
HH_FOR_OSS_PND_NUM
HH_FOR_OSS_S_PND_NUM
HH_FOR_INFER_PND_NUM
HH_FOR_ASS_SOC_PND_NUM
HH_FOR_EDU_PND_NUM
HH_FOR_PSI_PND_NUM
HH_FOR_MED_PND_NUM
HH_FOR_FISIAT_PND_NUM
HH_FOR_FISIOT_PND_NUM
COSTO_AUS_INCONT_NUM
COSTO_AUS_ALTRO_NUM
HH_ASS_DIR_PER_VOL_NUM
/**/
INCIDENZA_FOR_COORD 	
INCIDENZA_FOR_OSS 		
INCIDENZA_FOR_INF 		
INCIDENZA_FOR_ASS_SOC 	
INCIDENZA_FOR_EDU 		
INCIDENZA_FOR_PSI 		
INCIDENZA_FOR_MED 		
INCIDENZA_FOR_FISIAT 	
INCIDENZA_FOR_FISIOT 	
/**/
COSTO_ORARIO_COORD 
COSTO_ORARIO_OSS 
COSTO_ORARIO_INFER 
COSTO_ORARIO_ASS_SOC 
COSTO_ORARIO_EDU 
COSTO_ORARIO_PSI 
COSTO_ORARIO_MED 
COSTO_ORARIO_FISIAT 
COSTO_ORARIO_FISIOT 
/**/
NATURA_GIURIDICA;
RUN; 

DATA ARCIPELAGO12;
RETAIN
ULSS_UDO
ULSS_UDO_NEW
ANNO_RILEVAZIONE
COD_UDO
REG_PROVV_CDS
REG_ENTE_GES
/*5.5-5.72*/
HH_SER_COORD_PD_NUM
HH_SER_OSS_PD_NUM
HH_SER_OSS_S_PD_NUM
HH_SER_INFER_PD_NUM
HH_SER_ASS_SOC_PD_NUM
HH_SER_EDU_PD_NUM
HH_SER_PSI_PD_NUM
HH_SER_MED_PD_NUM
HH_SER_FISIAT_PD_NUM
HH_SER_FISIOT_PD_NUM
COSTO_COORD_PD_NUM
COSTO_OSS_PD_NUM
COSTO_OSS_S_PD_NUM
COSTO_INFER_PD_NUM
COSTO_ASS_SOC_PD_NUM
COSTO_EDU_PD_NUM
COSTO_PSI_PD_NUM
COSTO_MED_PD_NUM
COSTO_FISIAT_PD_NUM
COSTO_FISIOT_PD_NUM
HH_FOR_COORD_PD_NUM
HH_FOR_OSS_PD_NUM
HH_FOR_OSS_S_PD_NUM
HH_FOR_INFER_PD_NUM
HH_FOR_ASS_SOC_PD_NUM
HH_FOR_EDU_PD_NUM
HH_FOR_PSI_PD_NUM
HH_FOR_MED_PD_NUM
HH_FOR_FISIAT_PD_NUM
HH_FOR_FISIOT_PD_NUM
GG_MATERNITA_PD_NUM
COSTO_MATERNITA_PD_NUM
HH_PULIZIE_PD_NUM
GG_MALATTIA_PD_NUM
COSTO_MALATTIA_PD_NUM
HH_SER_COORD_PND_NUM
HH_SER_OSS_PND_NUM
HH_SER_OSS_S_PND_NUM
HH_SER_INFER_PND_NUM
HH_SER_ASS_SOC_PND_NUM
HH_SER_EDU_PND_NUM
HH_SER_PSI_PND_NUM
HH_SER_MED_PND_NUM
HH_SER_FISIAT_PND_NUM
HH_SER_FISIOT_PND_NUM
COSTO_COORD_PND_NUM
COSTO_OSS_PND_NUM
COSTO_OSS_S_PND_NUM
COSTO_INFER_PND_NUM
COSTO_ASS_SOC_PND_NUM
COSTO_EDU_PND_NUM
COSTO_PSI_PND_NUM
COSTO_MED_PND_NUM
COSTO_FISIAT_PND_NUM
COSTO_FISIOT_PND_NUM
HH_FOR_COORD_PND_NUM
HH_FOR_OSS_PND_NUM
HH_FOR_OSS_S_PND_NUM
HH_FOR_INFER_PND_NUM
HH_FOR_ASS_SOC_PND_NUM
HH_FOR_EDU_PND_NUM
HH_FOR_PSI_PND_NUM
HH_FOR_MED_PND_NUM
HH_FOR_FISIAT_PND_NUM
HH_FOR_FISIOT_PND_NUM
COSTO_AUS_INCONT_NUM
COSTO_AUS_ALTRO_NUM
HH_ASS_DIR_PER_VOL_NUM
/**/
INCIDENZA_FOR_COORD 	
INCIDENZA_FOR_OSS 		
INCIDENZA_FOR_INF 		
INCIDENZA_FOR_ASS_SOC 	
INCIDENZA_FOR_EDU 		
INCIDENZA_FOR_PSI 		
INCIDENZA_FOR_MED 		
INCIDENZA_FOR_FISIAT 	
INCIDENZA_FOR_FISIOT 	
/**/
COSTO_ORARIO_COORD 
COSTO_ORARIO_OSS 
COSTO_ORARIO_INFER 
COSTO_ORARIO_ASS_SOC 
COSTO_ORARIO_EDU 
COSTO_ORARIO_PSI 
COSTO_ORARIO_MED 
COSTO_ORARIO_FISIAT 
COSTO_ORARIO_FISIOT 
/**/
NATURA_GIURIDICA;
SET CDS_UDO; 
RUN; 

%mend; 

%let anno=2017;
%let fase=12;
%let fase_cds=0;

%set_udo;
%set_cds;
%tabella_012;
data t2016; set arcipelago12; run; 
data t2017; set arcipelago12; run; 
data arcipelago12ok; set t2016 t2017; run; 
